# Generated by Django 3.2 on 2021-05-21 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='company_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RegistrationApp.basiccompanydetails'),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='company_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RegistrationApp.basiccompanydetails'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='company_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RegistrationApp.basiccompanydetails'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
