# Generated by Django 3.2 on 2021-06-18 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalselfregistration',
            name='registration_status',
        ),
        migrations.RemoveField(
            model_name='selfregistration',
            name='registration_status',
        ),
    ]
