# Generated by Django 3.2 on 2021-07-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfregistration',
            name='profile_cover_photo',
            field=models.FileField(null=True, upload_to='coverphoto'),
        ),
    ]
