# Generated by Django 3.2 on 2021-06-04 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basiccompanydetails',
            name='company_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='basiccompanydetails',
            name='gst_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalbasiccompanydetails',
            name='company_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalbasiccompanydetails',
            name='gst_number',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='HistoricalBasicCompanyDetails_Others',
            fields=[
                ('company_name', models.CharField(max_length=200)),
                ('company_code', models.CharField(db_index=True, max_length=20)),
                ('company_established', models.CharField(max_length=200)),
                ('industrial_scale', models.CharField(max_length=150)),
                ('market_location', models.CharField(max_length=150)),
                ('company_type', models.CharField(max_length=200)),
                ('tax_id_or_vat', models.CharField(max_length=200)),
                ('currency', models.CharField(db_index=True, max_length=30)),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('updated_on', models.DateTimeField(blank=True, editable=False)),
                ('created_by', models.BigIntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical basic company details_ others',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BasicCompanyDetails_Others',
            fields=[
                ('company_name', models.CharField(max_length=200)),
                ('company_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company_established', models.CharField(max_length=200)),
                ('industrial_scale', models.CharField(max_length=150)),
                ('market_location', models.CharField(max_length=150)),
                ('company_type', models.CharField(max_length=200)),
                ('tax_id_or_vat', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=30, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField()),
                ('updated_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'BasicCompanyDetails_Others',
            },
        ),
    ]
