# Generated by Django 3.2 on 2021-08-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0002_auto_20210805_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basiccompanydetails',
            name='company_code',
            field=models.CharField(max_length=80, primary_key=True, serialize=False),
        ),
    ]
