# Generated by Django 3.2 on 2021-06-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0002_auto_20210604_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basiccompanydetails_others',
            name='currency',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalbasiccompanydetails_others',
            name='currency',
            field=models.CharField(max_length=30),
        ),
    ]
