# Generated by Django 3.2 on 2021-08-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0003_alter_basiccompanydetails_company_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basiccompanydetails',
            name='company_code',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
