# Generated by Django 3.2 on 2021-06-05 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0003_auto_20210604_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress_Others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_address_others', models.TextField(max_length=500)),
                ('ship_country_others', models.CharField(max_length=200)),
                ('ship_state_others', models.CharField(max_length=200)),
                ('ship_city_others', models.CharField(max_length=200)),
                ('ship_pincode_others', models.BigIntegerField()),
                ('ship_landmark_others', models.CharField(blank=True, max_length=50)),
                ('ship_location_others', models.CharField(blank=True, max_length=200)),
                ('created_on_others', models.DateTimeField(auto_now_add=True)),
                ('updated_on_others', models.DateTimeField(auto_now=True)),
                ('created_by_others', models.BigIntegerField()),
                ('company_code_others', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RegistrationApp.basiccompanydetails_others')),
                ('updated_by_others', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ShippingAddress_Others',
            },
        ),
        migrations.CreateModel(
            name='HistoricalShippingAddress_Others',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ship_address_others', models.TextField(max_length=500)),
                ('ship_country_others', models.CharField(max_length=200)),
                ('ship_state_others', models.CharField(max_length=200)),
                ('ship_city_others', models.CharField(max_length=200)),
                ('ship_pincode_others', models.BigIntegerField()),
                ('ship_landmark_others', models.CharField(blank=True, max_length=50)),
                ('ship_location_others', models.CharField(blank=True, max_length=200)),
                ('created_on_others', models.DateTimeField(blank=True, editable=False)),
                ('updated_on_others', models.DateTimeField(blank=True, editable=False)),
                ('created_by_others', models.BigIntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company_code_others', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='RegistrationApp.basiccompanydetails_others')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by_others', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical shipping address_ others',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBillingAddress_Others',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('bill_address_others', models.TextField(max_length=500)),
                ('bill_country_others', models.CharField(max_length=200)),
                ('bill_state_others', models.CharField(max_length=200)),
                ('bill_city_others', models.CharField(max_length=200)),
                ('bill_pincode_others', models.IntegerField()),
                ('bill_landmark_others', models.CharField(blank=True, max_length=50)),
                ('bill_location_others', models.CharField(blank=True, max_length=200)),
                ('created_on_others', models.DateTimeField(blank=True, editable=False)),
                ('updated_on_others', models.DateTimeField(blank=True, editable=False)),
                ('created_by_others', models.BigIntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company_code_others', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='RegistrationApp.basiccompanydetails_others')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by_others', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical billing address_ others',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BillingAddress_Others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_address_others', models.TextField(max_length=500)),
                ('bill_country_others', models.CharField(max_length=200)),
                ('bill_state_others', models.CharField(max_length=200)),
                ('bill_city_others', models.CharField(max_length=200)),
                ('bill_pincode_others', models.IntegerField()),
                ('bill_landmark_others', models.CharField(blank=True, max_length=50)),
                ('bill_location_others', models.CharField(blank=True, max_length=200)),
                ('created_on_others', models.DateTimeField(auto_now_add=True)),
                ('updated_on_others', models.DateTimeField(auto_now=True)),
                ('created_by_others', models.BigIntegerField()),
                ('company_code_others', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RegistrationApp.basiccompanydetails_others')),
                ('updated_by_others', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'BillingAddress_Others',
            },
        ),
    ]
