# Generated by Django 3.2 on 2021-07-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0003_auto_20210622_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallegaldocuments',
            name='document',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicallegaldocuments',
            name='document_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='legaldocuments',
            name='document',
            field=models.FileField(upload_to='static/legalfiles'),
        ),
        migrations.AlterField(
            model_name='legaldocuments',
            name='document_name',
            field=models.CharField(max_length=100),
        ),
    ]
