# Generated by Django 3.2 on 2021-07-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0004_auto_20210727_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeregistration',
            name='employee_user_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
