# Generated by Django 3.2 on 2021-06-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0004_billingaddress_others_historicalbillingaddress_others_historicalshippingaddress_others_shippingaddre'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='iban_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='micr_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='swift_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalbankdetails',
            name='iban_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalbankdetails',
            name='micr_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalbankdetails',
            name='swift_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
