# Generated by Django 3.2 on 2021-08-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0004_alter_basiccompanydetails_company_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basiccompanydetails',
            name='company_code',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
