# Generated by Django 3.2 on 2021-05-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0004_auto_20210524_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalselfregistration',
            name='profile_cover_photo',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='selfregistration',
            name='profile_cover_photo',
            field=models.FileField(null=True, upload_to='static/coverphoto'),
        ),
        migrations.AlterField(
            model_name='historicalselfregistration_sample',
            name='profile_cover_photo',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='legaldocuments',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='static/legalfiles'),
        ),
        migrations.AlterField(
            model_name='selfregistration_sample',
            name='profile_cover_photo',
            field=models.FileField(null=True, upload_to='static/coverphoto'),
        ),
    ]
