# Generated by Django 3.2 on 2021-06-11 14:10

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0005_auto_20210609_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_CompanyDetails',
            fields=[
                ('emp_company_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('emp_company_name', models.CharField(max_length=200)),
                ('emp_company_code', models.CharField(max_length=20, unique=True)),
                ('emp_tax_id_or_vat', models.CharField(max_length=200)),
                ('emp_company_established', models.CharField(max_length=200)),
                ('emp_industrial_scale', models.CharField(max_length=150)),
                ('emp_market_location', models.CharField(max_length=150)),
                ('emp_company_type', models.CharField(max_length=200)),
                ('emp_currency', models.CharField(max_length=30)),
                ('emp_bill_address', models.TextField(max_length=500)),
                ('emp_bill_country', models.CharField(max_length=200)),
                ('emp_bill_state', models.CharField(max_length=200)),
                ('emp_bill_city', models.CharField(max_length=200)),
                ('emp_bill_pincode', models.IntegerField()),
                ('emp_bill_landmark', models.CharField(blank=True, max_length=50)),
                ('emp_bill_location', models.CharField(blank=True, max_length=200)),
                ('emp_ship_address', models.TextField(max_length=500)),
                ('emp_ship_country', models.CharField(max_length=200)),
                ('emp_ship_state', models.CharField(max_length=200)),
                ('emp_ship_city', models.CharField(max_length=200)),
                ('emp_ship_pincode', models.BigIntegerField()),
                ('emp_ship_landmark', models.CharField(blank=True, max_length=50)),
                ('emp_ship_location', models.CharField(blank=True, max_length=200)),
                ('emp_created_on', models.DateTimeField(auto_now_add=True)),
                ('emp_updated_on', models.DateTimeField(auto_now=True)),
                ('emp_created_by', models.BigIntegerField()),
            ],
            options={
                'db_table': 'Employee_CompanyDetails',
            },
        ),
        migrations.CreateModel(
            name='EmployeeRegistration',
            fields=[
                ('emp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100, unique=True)),
                ('phone_no', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=300)),
                ('created_on_others', models.DateTimeField(auto_now_add=True)),
                ('updated_on_others', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'EmployeeRegistration',
            },
        ),
        migrations.CreateModel(
            name='HistoricalEmployee_IndustryInfo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('emp_nature_of_business', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=800), size=None)),
                ('emp_supply_capabilites', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=800), size=None)),
                ('emp_industry_to_serve', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=800), size=None)),
                ('emp_created_on', models.DateTimeField(blank=True, editable=False)),
                ('emp_updated_on', models.DateTimeField(blank=True, editable=False)),
                ('emp_created_by', models.BigIntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('emp_company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='RegistrationApp.employee_companydetails')),
                ('emp_updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='RegistrationApp.employeeregistration')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical employee_ industry info',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEmployee_CompanyDetails',
            fields=[
                ('emp_company_id', models.BigIntegerField(blank=True, db_index=True)),
                ('emp_company_name', models.CharField(max_length=200)),
                ('emp_company_code', models.CharField(db_index=True, max_length=20)),
                ('emp_tax_id_or_vat', models.CharField(max_length=200)),
                ('emp_company_established', models.CharField(max_length=200)),
                ('emp_industrial_scale', models.CharField(max_length=150)),
                ('emp_market_location', models.CharField(max_length=150)),
                ('emp_company_type', models.CharField(max_length=200)),
                ('emp_currency', models.CharField(max_length=30)),
                ('emp_bill_address', models.TextField(max_length=500)),
                ('emp_bill_country', models.CharField(max_length=200)),
                ('emp_bill_state', models.CharField(max_length=200)),
                ('emp_bill_city', models.CharField(max_length=200)),
                ('emp_bill_pincode', models.IntegerField()),
                ('emp_bill_landmark', models.CharField(blank=True, max_length=50)),
                ('emp_bill_location', models.CharField(blank=True, max_length=200)),
                ('emp_ship_address', models.TextField(max_length=500)),
                ('emp_ship_country', models.CharField(max_length=200)),
                ('emp_ship_state', models.CharField(max_length=200)),
                ('emp_ship_city', models.CharField(max_length=200)),
                ('emp_ship_pincode', models.BigIntegerField()),
                ('emp_ship_landmark', models.CharField(blank=True, max_length=50)),
                ('emp_ship_location', models.CharField(blank=True, max_length=200)),
                ('emp_created_on', models.DateTimeField(blank=True, editable=False)),
                ('emp_updated_on', models.DateTimeField(blank=True, editable=False)),
                ('emp_created_by', models.BigIntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('emp_updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='RegistrationApp.employeeregistration')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical employee_ company details',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Employee_IndustryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_nature_of_business', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=800), size=None)),
                ('emp_supply_capabilites', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=800), size=None)),
                ('emp_industry_to_serve', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=800), size=None)),
                ('emp_created_on', models.DateTimeField(auto_now_add=True)),
                ('emp_updated_on', models.DateTimeField(auto_now=True)),
                ('emp_created_by', models.BigIntegerField()),
                ('emp_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RegistrationApp.employee_companydetails')),
                ('emp_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RegistrationApp.employeeregistration')),
            ],
            options={
                'db_table': 'Employee_IndustryInfo',
            },
        ),
        migrations.AddField(
            model_name='employee_companydetails',
            name='emp_updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RegistrationApp.employeeregistration'),
        ),
    ]
