# Generated by Django 3.2 on 2021-05-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0005_auto_20210525_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='bill_state',
            field=models.CharField(default='karnataka', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalbillingaddress',
            name='bill_state',
            field=models.CharField(default='karnataka', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalshippingaddress',
            name='ship_state',
            field=models.CharField(default='karnataka', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='ship_state',
            field=models.CharField(default='karnataka', max_length=200),
            preserve_default=False,
        ),
    ]
