# Generated by Django 3.2 on 2021-07-30 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0006_auto_20210730_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selfregistration',
            old_name='desgination',
            new_name='designation',
        ),
    ]
