# Generated by Django 3.2 on 2021-06-11 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0006_employee_companydetails_employee_industryinfo_employeeregistration_historicalemployee_companydetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeregistration',
            name='confrim_password',
        ),
    ]
