# Generated by Django 3.2 on 2021-06-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0006_auto_20210611_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeregistration',
            name='employee_usertype',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
