# Generated by Django 3.2 on 2021-06-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0007_remove_employeeregistration_confrim_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeregistration',
            name='password',
            field=models.CharField(max_length=300),
        ),
    ]
