# Generated by Django 3.2 on 2021-07-30 13:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0007_rename_desgination_selfregistration_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfregistration',
            name='business_to_serve',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='selfregistration',
            name='nature_of_business',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), null=True, size=None),
        ),
    ]
