# Generated by Django 3.1.5 on 2021-08-05 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0008_auto_20210805_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrialinfo',
            name='company_code',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='RegistrationApp.basiccompanydetails'),
        ),
    ]
