# Generated by Django 3.2 on 2021-08-02 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0009_auto_20210802_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_industryinfo',
            name='emp_updated_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
