# Generated by Django 3.2 on 2021-08-09 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0010_auto_20210806_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
