# Generated by Django 3.2 on 2021-08-02 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0010_alter_employee_industryinfo_emp_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='company_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RegistrationApp.basiccompanydetails'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='company_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RegistrationApp.basiccompanydetails'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
