# Generated by Django 3.2 on 2021-08-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0011_alter_contactdetails_updated_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdetails',
            old_name='currency',
            new_name='division',
        ),
        migrations.RemoveField(
            model_name='communicationdetails',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='communicationdetails',
            name='department',
        ),
        migrations.RemoveField(
            model_name='communicationdetails',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='communicationdetails',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='communicationdetails',
            name='name',
        ),
        migrations.RemoveField(
            model_name='communicationdetails',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='communicationdetails',
            name='region',
        ),
        migrations.RemoveField(
            model_name='communicationdetails',
            name='unit_address',
        ),
        migrations.AddField(
            model_name='communicationdetails',
            name='country',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='communicationdetails',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='communicationdetails',
            name='unit_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
