# Generated by Django 3.2 on 2021-08-02 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0011_auto_20210802_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='emp_company_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RegistrationApp.employee_companydetails'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='emp_company_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RegistrationApp.employee_companydetails'),
        ),
    ]
