# Generated by Django 3.2 on 2021-10-20 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0020_alter_basiccompanydetails_msme_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basiccompanydetails',
            name='company_established',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='basiccompanydetails',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='basiccompanydetails',
            name='company_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='basiccompanydetails',
            name='created_by',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basiccompanydetails',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='basiccompanydetails',
            name='gst_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='basiccompanydetails',
            name='industrial_scale',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='basiccompanydetails',
            name='listing_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='basiccompanydetails',
            name='pan_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='basiccompanydetails',
            name='registered_iec',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='basiccompanydetails',
            name='tax_payer_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='basiccompanydetails',
            name='updated_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='basiccompanydetails',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
