# Generated by Django 3.2.9 on 2022-01-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0025_auto_20211230_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='admin_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basiccompanydetails',
            name='admin_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='admin_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='industrialhierarchy',
            name='admin_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='industrialinfo',
            name='admin_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='legaldocuments',
            name='admin_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selfregistration',
            name='admin_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selfregistration_sample',
            name='admin_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='admin_create',
            field=models.BooleanField(default=False),
        ),
    ]
