# Generated by Django 3.2.9 on 2022-01-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0026_auto_20220104_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfregistration',
            name='email_verify',
            field=models.CharField(blank=True, default=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='selfregistration',
            name='phone_verify',
            field=models.CharField(blank=True, default=False, max_length=20, null=True),
        ),
    ]
