# Generated by Django 3.2.9 on 2022-03-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0028_postenquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postenquiry',
            name='created_by',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
