# Generated by Django 3.2 on 2021-08-03 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LandingPageApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyrating',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LandingPageApp.companyreview'),
        ),
        migrations.AddField(
            model_name='companyrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='companyrating',
            unique_together={('user', 'company')},
        ),
        migrations.AlterIndexTogether(
            name='companyrating',
            index_together={('user', 'company')},
        ),
    ]
