# Generated by Django 3.1.5 on 2021-08-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPageApp', '0006_auto_20210820_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyrating',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='companyreview',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
