# Generated by Django 3.2.9 on 2021-12-16 08:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0023_auto_20211103_1215'),
        ('LandingPageApp', '0011_auto_20211216_0617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyreview',
            old_name='user_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='companyreview',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='companyreview',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='companyreview',
            name='company_review',
        ),
        migrations.AddField(
            model_name='companyreview',
            name='company_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RegistrationApp.basiccompanydetails'),
        ),
        migrations.AddField(
            model_name='companyreview',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='companyreview',
            name='rating',
            field=models.IntegerField(default='4', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyreview',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyreview',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.DeleteModel(
            name='CompanyRating',
        ),
    ]
