# Generated by Django 3.2.9 on 2021-12-16 08:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0023_auto_20211103_1215'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LandingPageApp', '0012_auto_20211216_0845'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyReview',
            new_name='CompanyReviewAndRating',
        ),
        migrations.AlterModelTable(
            name='companyreviewandrating',
            table='CompanyReviewAndRating',
        ),
    ]
