# Generated by Django 3.2.9 on 2021-12-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPageApp', '0013_auto_20211216_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreviewandrating',
            name='company_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
