# Generated by Django 3.2.9 on 2021-12-16 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPageApp', '0014_companyreviewandrating_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyreviewandrating',
            name='company_name',
        ),
    ]
