# Generated by Django 3.2.9 on 2021-12-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPageApp', '0015_remove_companyreviewandrating_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreviewandrating',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
