# Generated by Django 3.2.3 on 2021-12-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPageApp', '0017_auto_20211229_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyreviewandrating',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
