# Generated by Django 3.2.9 on 2022-02-07 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LandingPageApp', '0018_alter_companyreviewandrating_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.TextField(blank=True, null=True)),
                ('company_name_sender', models.CharField(blank=True, max_length=500, null=True)),
                ('company_name_receiver', models.CharField(blank=True, max_length=500, null=True)),
                ('sender_files', models.FileField(blank=True, null=True, upload_to='MessagesAttachment')),
                ('receiver_files', models.FileField(blank=True, null=True, upload_to='MessagesAttachment')),
                ('sender_images', models.FileField(blank=True, null=True, upload_to='MessageImages')),
                ('receiver_images', models.FileField(blank=True, null=True, upload_to='MessageImages')),
                ('sender_designation', models.CharField(blank=True, max_length=200, null=True)),
                ('receiver_designation', models.CharField(blank=True, max_length=200, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Message',
                'ordering': ('created_time',),
            },
        ),
        migrations.CreateModel(
            name='HistoricalMessage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('messages', models.TextField(blank=True, null=True)),
                ('company_name_sender', models.CharField(blank=True, max_length=500, null=True)),
                ('company_name_receiver', models.CharField(blank=True, max_length=500, null=True)),
                ('sender_files', models.TextField(blank=True, max_length=100, null=True)),
                ('receiver_files', models.TextField(blank=True, max_length=100, null=True)),
                ('sender_images', models.TextField(blank=True, max_length=100, null=True)),
                ('receiver_images', models.TextField(blank=True, max_length=100, null=True)),
                ('sender_designation', models.CharField(blank=True, max_length=200, null=True)),
                ('receiver_designation', models.CharField(blank=True, max_length=200, null=True)),
                ('created_time', models.DateTimeField(blank=True, editable=False)),
                ('is_read', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical message',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
