# Generated by Django 3.2.9 on 2022-02-22 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0051_auto_20220221_1745'),
        ('LandingPageApp', '0021_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmessage',
            name='vendor_product_pk',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='MaterialApp.vendorproduct_basicdetails'),
        ),
        migrations.AddField(
            model_name='message',
            name='vendor_product_pk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MaterialApp.vendorproduct_basicdetails'),
        ),
    ]
