# Generated by Django 3.2.9 on 2022-03-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPageApp', '0022_auto_20220222_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmessage',
            name='source',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='source',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
