# Generated by Django 3.2.3 on 2022-03-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPageApp', '0023_auto_20220303_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmessage',
            name='get_vendor',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='get_vendor',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
