# Generated by Django 3.2.3 on 2022-03-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPageApp', '0024_auto_20220307_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmessage',
            name='rfq',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='rfq',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
