# Generated by Django 3.2.9 on 2022-03-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPageApp', '0025_auto_20220307_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmessage',
            name='enquiry',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='enquiry',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
