# Generated by Django 3.2 on 2021-07-10 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RfqCodeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfq_number', models.CharField(max_length=200)),
                ('prefix', models.CharField(blank=True, max_length=70, null=True)),
                ('numeric', models.CharField(max_length=30)),
                ('suffix', models.CharField(blank=True, max_length=70, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField()),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'RfqCodeSettings',
            },
        ),
        migrations.CreateModel(
            name='BuyerProductBidding',
            fields=[
                ('product_bidding_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_rfq_number', models.CharField(max_length=40, unique=True)),
                ('product_rfq_type', models.CharField(max_length=400)),
                ('product_rfq_status', models.CharField(default='Pending', max_length=50)),
                ('product_publish_date', models.CharField(max_length=100)),
                ('product_deadline_date', models.CharField(max_length=100)),
                ('product_delivery_date', models.CharField(max_length=100)),
                ('product_rfq_currency', models.CharField(blank=True, max_length=100, null=True)),
                ('product_rfq_category', models.CharField(blank=True, max_length=100, null=True)),
                ('product_department', models.CharField(max_length=300)),
                ('product_bill_address', models.TextField()),
                ('product_ship_address', models.TextField()),
                ('product_rfq_title', models.CharField(max_length=600)),
                ('bidding_numeric', models.CharField(max_length=30)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField()),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'BuyerProductBidding',
            },
        ),
        migrations.CreateModel(
            name='BiddingBuyerProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_item_code', models.CharField(max_length=100, unique=True)),
                ('buyer_item_name', models.CharField(max_length=100)),
                ('buyer_item_description', models.TextField(blank=True, null=True)),
                ('buyer_uom', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_category', models.CharField(max_length=500, null=True)),
                ('buyer_quantity', models.CharField(max_length=100)),
                ('buyer_document', models.FileField(blank=True, null=True, upload_to='BuyerProductFiles')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField()),
                ('buyer_rfq_number', models.CharField(max_length=100)),
                ('product_biddings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BiddingApp.buyerproductbidding')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'BiddingBuyerProductDetails',
            },
        ),
    ]
