# Generated by Django 3.2 on 2021-07-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiddingApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyerproductbidding',
            old_name='bidding_numeric',
            new_name='user_bidding_numeric',
        ),
        migrations.AddField(
            model_name='buyerproductbidding',
            name='user_rfq_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
