# Generated by Django 3.2 on 2021-07-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiddingApp', '0002_auto_20210710_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerproductbidding',
            name='product_rfq_number',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='buyerproductbidding',
            name='user_bidding_numeric',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
