# Generated by Django 3.2 on 2021-07-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiddingApp', '0003_auto_20210710_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerproductbidding',
            name='user_prefix',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
