# Generated by Django 3.2 on 2021-07-11 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BiddingApp', '0004_buyerproductbidding_user_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biddingbuyerproductdetails',
            name='product_biddings',
        ),
    ]
