# Generated by Django 3.2 on 2021-08-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiddingApp', '0004_auto_20210806_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvendorbiddingbuyerproductdetails',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendorbiddingbuyerproductdetails',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
