# Generated by Django 3.2 on 2021-08-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiddingApp', '0004_auto_20210727_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcelist_createitems',
            name='present_cost',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sourcelist_createitems',
            name='target_cost',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
