# Generated by Django 3.2 on 2021-07-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiddingApp', '0005_remove_biddingbuyerproductdetails_product_biddings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddingbuyerproductdetails',
            name='buyer_item_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
