# Generated by Django 3.2 on 2021-08-07 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BiddingApp', '0005_auto_20210806_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvendorproductbidding',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorproductbidding',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfq_number', models.CharField(blank=True, max_length=50, null=True)),
                ('rfq_title', models.CharField(blank=True, max_length=100, null=True)),
                ('PO_num', models.CharField(blank=True, max_length=50, null=True)),
                ('PO_date', models.DateField()),
                ('delievery_date', models.DateField()),
                ('PO_expirydate', models.DateField()),
                ('remind', models.DateField(blank=True, null=True)),
                ('delievery_days', models.CharField(blank=True, max_length=100, null=True)),
                ('vendorcode', models.CharField(max_length=30)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.TextField()),
                ('attachment1', models.FileField(blank=True, null=True, upload_to='POfile')),
                ('attachment2', models.FileField(blank=True, null=True, upload_to='POfile')),
                ('attachment3', models.FileField(blank=True, null=True, upload_to='POfile')),
                ('createdon', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedon', models.DateTimeField(auto_now=True, null=True)),
                ('updatedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PurchaseOrder',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPurchaseOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('rfq_number', models.CharField(blank=True, max_length=50, null=True)),
                ('rfq_title', models.CharField(blank=True, max_length=100, null=True)),
                ('PO_num', models.CharField(blank=True, max_length=50, null=True)),
                ('PO_date', models.DateField()),
                ('delievery_date', models.DateField()),
                ('PO_expirydate', models.DateField()),
                ('remind', models.DateField(blank=True, null=True)),
                ('delievery_days', models.CharField(blank=True, max_length=100, null=True)),
                ('vendorcode', models.CharField(max_length=30)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.TextField()),
                ('attachment1', models.TextField(blank=True, max_length=100, null=True)),
                ('attachment2', models.TextField(blank=True, max_length=100, null=True)),
                ('attachment3', models.TextField(blank=True, max_length=100, null=True)),
                ('createdon', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updatedon', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updatedby', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical purchase order',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
