# Generated by Django 3.2 on 2021-08-07 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BiddingApp', '0006_auto_20210807_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='updatedby',
        ),
        migrations.DeleteModel(
            name='HistoricalPurchaseOrder',
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
    ]
