# Generated by Django 3.2 on 2021-07-11 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BiddingApp', '0007_rfqtermsdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqtermsdescription',
            name='product_biddings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BiddingApp.buyerproductbidding'),
        ),
    ]
