# Generated by Django 3.2 on 2021-07-11 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BiddingApp', '0008_rfqtermsdescription_product_biddings'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRfqTermsDescription',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('rfq_number', models.CharField(max_length=200)),
                ('terms', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('updated_on', models.DateTimeField(blank=True, editable=False)),
                ('created_by', models.BigIntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product_biddings', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='BiddingApp.buyerproductbidding')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical rfq terms description',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBuyerProductBidding',
            fields=[
                ('product_bidding_id', models.BigIntegerField(blank=True, db_index=True)),
                ('product_rfq_number', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('user_rfq_number', models.CharField(blank=True, max_length=50, null=True)),
                ('user_bidding_numeric', models.CharField(max_length=30, null=True)),
                ('user_prefix', models.CharField(blank=True, max_length=50, null=True)),
                ('product_rfq_type', models.CharField(max_length=400)),
                ('product_rfq_status', models.CharField(default='Pending', max_length=50)),
                ('product_publish_date', models.CharField(max_length=100)),
                ('product_deadline_date', models.CharField(max_length=100)),
                ('product_delivery_date', models.CharField(max_length=100)),
                ('product_rfq_currency', models.CharField(blank=True, max_length=100, null=True)),
                ('product_rfq_category', models.CharField(blank=True, max_length=100, null=True)),
                ('product_department', models.CharField(max_length=300)),
                ('product_bill_address', models.TextField()),
                ('product_ship_address', models.TextField()),
                ('product_rfq_title', models.CharField(max_length=600)),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('updated_on', models.DateTimeField(blank=True, editable=False)),
                ('created_by', models.BigIntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical buyer product bidding',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBiddingBuyerProductDetails',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('buyer_item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_item_name', models.CharField(max_length=100)),
                ('buyer_item_description', models.TextField(blank=True, null=True)),
                ('buyer_uom', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_category', models.CharField(max_length=500, null=True)),
                ('buyer_quantity', models.CharField(max_length=100)),
                ('buyer_document', models.TextField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('updated_on', models.DateTimeField(blank=True, editable=False)),
                ('created_by', models.BigIntegerField()),
                ('buyer_rfq_number', models.CharField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical bidding buyer product details',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
