# Generated by Django 3.2 on 2021-08-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiddingApp', '0008_awards_historicalawards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='deadline_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='awards',
            name='publish_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalawards',
            name='deadline_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalawards',
            name='publish_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
