# Generated by Django 3.2 on 2021-08-08 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BiddingApp', '0009_auto_20210808_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalawards',
            old_name='updatedby',
            new_name='updated_by',
        ),
        migrations.RemoveField(
            model_name='awards',
            name='createdon',
        ),
        migrations.RemoveField(
            model_name='awards',
            name='updatedby',
        ),
        migrations.RemoveField(
            model_name='awards',
            name='updatedon',
        ),
        migrations.RemoveField(
            model_name='historicalawards',
            name='createdon',
        ),
        migrations.RemoveField(
            model_name='historicalawards',
            name='updatedon',
        ),
        migrations.AddField(
            model_name='awards',
            name='created_by',
            field=models.BigIntegerField(default='2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='awards',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default='2021-08-06 13:09:54.406117+00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='awards',
            name='updated_by',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='RegistrationApp.selfregistration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='awards',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='historicalawards',
            name='created_by',
            field=models.BigIntegerField(default='2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalawards',
            name='created_on',
            field=models.DateTimeField(blank=True, default='2021-08-06 13:09:54.406117+00', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalawards',
            name='updated_on',
            field=models.DateTimeField(blank=True, default='2021-08-06 13:09:54.406117+00', editable=False),
            preserve_default=False,
        ),
    ]
