# Generated by Django 3.2 on 2021-08-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiddingApp', '0010_auto_20210808_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='created_by',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalawards',
            name='created_by',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
