# Generated by Django 3.2 on 2021-08-08 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BiddingApp', '0011_auto_20210808_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awards',
            name='frieght_cost',
        ),
        migrations.RemoveField(
            model_name='awards',
            name='p_f_charge',
        ),
        migrations.RemoveField(
            model_name='historicalawards',
            name='frieght_cost',
        ),
        migrations.RemoveField(
            model_name='historicalawards',
            name='p_f_charge',
        ),
    ]
