# Generated by Django 3.2 on 2021-08-11 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BiddingApp', '0012_auto_20210808_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='biddingbuyerproductdetails',
            name='product_rfq_type',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='historicalbiddingbuyerproductdetails',
            name='product_rfq_type',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='historicalrfqtermsdescription',
            name='product_rfq_type',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='rfqtermsdescription',
            name='product_rfq_type',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrfqtermsdescription',
            name='rfq_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rfqtermsdescription',
            name='rfq_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='HistoricalBiddingBuyerServiceDetails',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('service_buyer_item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('service_buyer_item_name', models.CharField(max_length=100)),
                ('service_buyer_item_description', models.TextField(blank=True, null=True)),
                ('service_buyer_uom', models.CharField(blank=True, max_length=100, null=True)),
                ('service_buyer_category', models.CharField(max_length=500, null=True)),
                ('service_buyer_quantity', models.CharField(max_length=100)),
                ('service_buyer_document', models.TextField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('updated_on', models.DateTimeField(blank=True, editable=False)),
                ('created_by', models.BigIntegerField()),
                ('service_buyer_rfq_number', models.CharField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical bidding buyer service details',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BiddingBuyerServiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_buyer_item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('service_buyer_item_name', models.CharField(max_length=100)),
                ('service_buyer_item_description', models.TextField(blank=True, null=True)),
                ('service_buyer_uom', models.CharField(blank=True, max_length=100, null=True)),
                ('service_buyer_category', models.CharField(max_length=500, null=True)),
                ('service_buyer_quantity', models.CharField(max_length=100)),
                ('service_buyer_document', models.FileField(blank=True, null=True, upload_to='BuyerServiceFiles')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField()),
                ('service_buyer_rfq_number', models.CharField(max_length=100)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'BiddingBuyerServiceDetails',
            },
        ),
    ]
