# Generated by Django 3.2 on 2021-08-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiddingApp', '0014_auto_20210811_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectvendorsforbiddingproduct',
            name='rfq_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
