# Generated by Django 3.1.5 on 2021-09-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiddingApp', '0019_auto_20210830_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcelist_createitems',
            name='present_cost',
        ),
        migrations.RemoveField(
            model_name='sourcelist_createitems',
            name='status',
        ),
        migrations.RemoveField(
            model_name='sourcelist_createitems',
            name='target_cost',
        ),
        migrations.AddField(
            model_name='sourcelist_createitems',
            name='deadline_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sourcelist_createitems',
            name='document_name1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sourcelist_createitems',
            name='document_name2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sourcelist_createitems',
            name='document_name3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sourcelist_createitems',
            name='publish_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
