# Generated by Django 3.1.5 on 2021-09-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiddingApp', '0020_auto_20210902_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcelist_createitems',
            name='item_code',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
