# Generated by Django 3.2 on 2021-09-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiddingApp', '0023_extendeddatelistbuyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='PO_num',
            field=models.CharField(db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='PO_num',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
