# Generated by Django 3.2 on 2021-09-14 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BiddingApp', '0024_auto_20210905_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceAwards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.CharField(blank=True, max_length=200, null=True)),
                ('source_type', models.CharField(blank=True, max_length=200, null=True)),
                ('source_item_type', models.CharField(blank=True, max_length=200, null=True)),
                ('source_item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('source_item_description', models.TextField(blank=True, null=True)),
                ('source_uom', models.CharField(blank=True, max_length=70, null=True)),
                ('source_delivery_charges', models.CharField(blank=True, max_length=200, null=True)),
                ('source_frieght_charges', models.CharField(blank=True, max_length=200, null=True)),
                ('source_pf_charges', models.CharField(blank=True, max_length=200, null=True)),
                ('source_product_category', models.CharField(blank=True, max_length=500, null=True)),
                ('source_priority', models.CharField(blank=True, max_length=50, null=True)),
                ('source_department', models.CharField(blank=True, max_length=150, null=True)),
                ('source_quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('source_unit_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('source_tax', models.CharField(blank=True, max_length=50, null=True)),
                ('source_discount', models.CharField(blank=True, max_length=50, null=True)),
                ('source_total_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField()),
                ('company_name', models.CharField(blank=True, max_length=300, null=True)),
                ('company_code', models.CharField(blank=True, max_length=100, null=True)),
                ('source_po_status', models.CharField(default='Pending', max_length=200)),
                ('source_create_pk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BiddingApp.sourcelist_createitems')),
                ('source_publish_pk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BiddingApp.sourcepublish')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SourceAwards',
            },
        ),
    ]
