# Generated by Django 3.2 on 2021-09-18 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BiddingApp', '0025_sourceawards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalserviceawards',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalserviceawards',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='machinaryawards',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='serviceawards',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='HistoricalMachinaryAwards',
        ),
        migrations.DeleteModel(
            name='HistoricalServiceAwards',
        ),
        migrations.DeleteModel(
            name='MachinaryAwards',
        ),
        migrations.DeleteModel(
            name='ServiceAwards',
        ),
    ]
