# Generated by Django 3.2 on 2021-09-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiddingApp', '0029_auto_20210923_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerproductbidding',
            name='product_delivery_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyerproductbidding',
            name='product_department',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='buyerproductbidding',
            name='product_rfq_category',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbuyerproductbidding',
            name='product_delivery_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbuyerproductbidding',
            name='product_department',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbuyerproductbidding',
            name='product_rfq_category',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
