# Generated by Django 3.2 on 2021-09-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiddingApp', '0030_auto_20210927_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerproductbidding',
            name='email_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalbuyerproductbidding',
            name='email_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
