# Generated by Django 3.2 on 2021-09-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiddingApp', '0031_auto_20210927_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='attachment1',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='attachment2',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='attachment3',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='attachment1',
            field=models.FileField(null=True, upload_to='POfile'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='attachment2',
            field=models.FileField(null=True, upload_to='POfile'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='attachment3',
            field=models.FileField(null=True, upload_to='POfile'),
        ),
    ]
