# Generated by Django 3.2 on 2021-09-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiddingApp', '0032_auto_20210927_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='attachment1',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='attachment2',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='attachment3',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='attachment1',
            field=models.FileField(blank=True, null=True, upload_to='POfile'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='attachment2',
            field=models.FileField(blank=True, null=True, upload_to='POfile'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='attachment3',
            field=models.FileField(blank=True, null=True, upload_to='POfile'),
        ),
    ]
