# Generated by Django 3.2 on 2021-09-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiddingApp', '0033_auto_20210927_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcelist_createitems',
            name='annual_consumption',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sourcelist_createitems',
            name='delivery',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sourcelist_createitems',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sourcelist_createitems',
            name='item_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sourcelist_createitems',
            name='priority',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sourcelist_createitems',
            name='source_required_city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
