# Generated by Django 3.2 on 2021-10-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiddingApp', '0034_auto_20210929_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
