# Generated by Django 3.2 on 2021-10-18 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0038_alter_openleadstermsdescription_rfq_number'),
        ('BiddingApp', '0035_auto_20211005_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceawards',
            name='admins',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister'),
        ),
        migrations.AddField(
            model_name='sourcelist_createitems',
            name='admins',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister'),
        ),
        migrations.AddField(
            model_name='sourcelist_createitems',
            name='source_status',
            field=models.CharField(blank=True, default='Pending', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sourcepublish',
            name='admins',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister'),
        ),
    ]
