# Generated by Django 3.2.3 on 2021-11-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiddingApp', '0036_auto_20211018_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcelist_createitems',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sourcelist_createitems',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sourcelist_createitems',
            name='warranty',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
