# Generated by Django 3.2.3 on 2021-11-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiddingApp', '0037_auto_20211109_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcelist_createitems',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sourcelist_createitems',
            name='maincore',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
