# Generated by Django 3.2.3 on 2021-11-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiddingApp', '0038_auto_20211110_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcelist_createitems',
            name='get_vendors',
            field=models.CharField(blank=True, default='False', max_length=100, null=True),
        ),
    ]
