# Generated by Django 3.2.3 on 2021-11-16 13:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiddingApp', '0041_auto_20211116_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddingtermmastersettings',
            name='terms_description',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=list, max_length=800, null=True), size=None),
        ),
    ]
