# Generated by Django 3.2.3 on 2021-11-16 13:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiddingApp', '0042_alter_biddingtermmastersettings_terms_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddingtermmastersettings',
            name='terms_description',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=800, null=True), size=None),
        ),
    ]
