# Generated by Django 3.1.5 on 2021-12-29 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BiddingApp', '0047_auto_20211229_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvendorrfqtermsdescriptionopencommonbid',
            name='vendor_product_biddings',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='BiddingApp.vendorproductbiddingopencommonbid'),
        ),
        migrations.AlterField(
            model_name='vendorrfqtermsdescriptionopencommonbid',
            name='vendor_product_biddings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BiddingApp.vendorproductbiddingopencommonbid'),
        ),
    ]
