# Generated by Django 3.2.9 on 2022-02-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiddingApp', '0050_auto_20211230_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcepublish',
            name='source_payment_terms',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sourcepublish',
            name='source_warranty',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
