# Generated by Django 3.2.9 on 2022-02-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiddingApp', '0052_sourcepurchaseorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcepurchaseorder',
            name='awarded_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
