# Generated by Django 3.2.9 on 2022-02-11 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BiddingApp', '0053_alter_sourcepurchaseorder_awarded_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcepurchaseorder',
            name='source_award_pk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BiddingApp.sourceawards'),
        ),
        migrations.AddField(
            model_name='sourcepurchaseorder',
            name='source_publish_pk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BiddingApp.sourcepublish'),
        ),
    ]
