# Generated by Django 3.2.9 on 2022-02-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiddingApp', '0054_auto_20220211_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcepurchaseorder',
            name='po_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
