# Generated by Django 3.2.9 on 2022-03-02 14:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiddingApp', '0055_alter_sourcepurchaseorder_po_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='biddingtermmastersettings',
            name='terms_code',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=800, null=True), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biddingtermmastersettings',
            name='terms_status',
            field=models.CharField(blank=True, default='Active', max_length=100, null=True),
        ),
    ]
