# Generated by Django 3.2.9 on 2022-03-03 14:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiddingApp', '0056_auto_20220302_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biddingtermmastersettings',
            old_name='terms_code',
            new_name='description_code',
        ),
        migrations.AlterField(
            model_name='biddingtermmastersettings',
            name='terms_status',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='Active', max_length=800, null=True), size=None),
        ),
    ]
