# Generated by Django 3.2.3 on 2022-03-07 15:10

import django.contrib.postgres.fields
from django.db import migrations, models
from django.conf import settings
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('BiddingApp', '0058_addtermstorfqbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtermstorfqbid',
            name='terms_description',
            field=(django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=800, null=True), default=[], size=None)
                   if not getattr(settings, 'USE_SQLITE', False)
                   else models.TextField(blank=True, null=True)),
            preserve_default=False,
        ),
    ]
