# Generated by Django 3.2.9 on 2022-03-09 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BiddingApp', '0059_addtermstorfqbid_terms_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtermstorfqbid',
            name='terms_pk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BiddingApp.biddingtermmastersettings'),
        ),
    ]
