# Generated by Django 3.2.9 on 2022-03-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiddingApp', '0060_addtermstorfqbid_terms_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcepurchaseorder',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourcepurchaseorder',
            name='po_status',
            field=models.CharField(blank=True, default='PO_Sent', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sourcepurchaseorder',
            name='priority',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sourcepurchaseorder',
            name='source',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
