# Generated by Django 3.2.9 on 2022-03-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiddingApp', '0061_auto_20220310_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcelist_createitems',
            name='sub_category',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
