# Generated by Django 3.2 on 2021-06-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProductsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_sector', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('sub_category', models.CharField(blank=True, max_length=100)),
                ('product_category', models.CharField(blank=True, max_length=100)),
                ('product_subcategory', models.CharField(blank=True, max_length=100)),
                ('product_type', models.CharField(max_length=100, null=True)),
                ('type_of_product', models.CharField(max_length=100, null=True)),
                ('product_code', models.CharField(max_length=100, null=True, unique=True)),
                ('product_name', models.CharField(max_length=100, null=True)),
                ('product_description', models.CharField(max_length=100, null=True)),
                ('product_document', models.FileField(blank=True, upload_to='ProductsFile')),
                ('numeric', models.BigIntegerField(null=True)),
                ('add_image1', models.FileField(blank=True, null=True, upload_to='vendorproductimage')),
                ('add_image2', models.FileField(blank=True, null=True, upload_to='vendorproductimage')),
                ('add_image3', models.FileField(blank=True, null=True, upload_to='vendorproductimage')),
                ('add_image4', models.FileField(blank=True, null=True, upload_to='vendorproductimage')),
                ('uom', models.CharField(blank=True, max_length=100)),
                ('quantity', models.CharField(blank=True, max_length=100)),
                ('hsn_sac', models.CharField(blank=True, max_length=100)),
                ('unit_price', models.CharField(blank=True, max_length=100)),
                ('discount', models.CharField(blank=True, max_length=50)),
                ('tax', models.CharField(blank=True, max_length=100)),
                ('sku_id', models.CharField(blank=True, max_length=100)),
                ('country_of_origin', models.CharField(blank=True, max_length=50)),
                ('currency', models.CharField(blank=True, max_length=50)),
                ('p_andf_charges', models.CharField(blank=True, max_length=100)),
                ('fright_charges', models.CharField(blank=True, max_length=100)),
                ('warrenty_or_guarantee', models.CharField(blank=True, max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField()),
            ],
            options={
                'db_table': 'VendorProductsDetail',
            },
        ),
    ]
