# Generated by Django 3.2 on 2021-05-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralProductsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warrenty', models.CharField(blank=True, max_length=100)),
                ('guarantee', models.CharField(blank=True, max_length=100)),
                ('after_sale_service', models.CharField(blank=True, max_length=100)),
                ('not_covered_WorG', models.CharField(blank=True, max_length=100)),
                ('industry_to_use', models.CharField(blank=True, max_length=100)),
                ('brand_make', models.CharField(blank=True, max_length=100)),
                ('model_no', models.CharField(blank=True, max_length=100)),
                ('part_no', models.CharField(blank=True, max_length=100)),
                ('alternate_parts', models.CharField(blank=True, max_length=100)),
                ('usage_application', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('min_order_quantity', models.CharField(blank=True, max_length=100)),
                ('packing_type', models.CharField(blank=True, max_length=100)),
                ('delievery_days', models.CharField(blank=True, max_length=100)),
                ('industries_sectors', models.CharField(blank=True, max_length=100)),
                ('standard_measures', models.CharField(blank=True, max_length=100)),
                ('item_weight', models.CharField(blank=True, max_length=100)),
                ('after_packing_weight', models.CharField(blank=True, max_length=100)),
                ('product_length', models.CharField(blank=True, max_length=100)),
                ('product_width', models.CharField(blank=True, max_length=100)),
                ('product_height', models.CharField(blank=True, max_length=100)),
                ('shipping_uom', models.CharField(blank=True, max_length=100)),
                ('shipping_weight', models.CharField(blank=True, max_length=100)),
                ('ship_via', models.CharField(blank=True, max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField()),
            ],
            options={
                'db_table': 'ProductGeneralDetails',
            },
        ),
        migrations.CreateModel(
            name='PricingOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.CharField(blank=True, max_length=100)),
                ('discount', models.CharField(blank=True, max_length=50)),
                ('final_price', models.CharField(blank=True, max_length=100)),
                ('tax', models.CharField(blank=True, max_length=50)),
                ('total_amount', models.CharField(blank=True, max_length=100)),
                ('manufacturer_mrp', models.CharField(blank=True, max_length=100)),
                ('net_price', models.CharField(blank=True, max_length=100)),
                ('offering_quantity', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('offering_days', models.CharField(blank=True, max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField()),
            ],
            options={
                'db_table': 'PricingOffer',
            },
        ),
        migrations.CreateModel(
            name='ProductFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField()),
            ],
            options={
                'db_table': 'ProductFeatures',
            },
        ),
        migrations.CreateModel(
            name='TechnicalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField()),
            ],
            options={
                'db_table': 'TechnicalDetails',
            },
        ),
        migrations.CreateModel(
            name='VendorProductsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_sector', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('sub_category', models.CharField(blank=True, max_length=100)),
                ('product_category', models.CharField(blank=True, max_length=100)),
                ('product_subcategory', models.CharField(blank=True, max_length=100)),
                ('product_type', models.CharField(max_length=100, null=True)),
                ('product_code', models.CharField(max_length=100, null=True)),
                ('product_name', models.CharField(max_length=100, null=True)),
                ('product_description', models.CharField(max_length=100, null=True)),
                ('product_document', models.FileField(blank=True, upload_to='ProductsFile')),
                ('numeric', models.CharField(blank=True, max_length=100)),
                ('addImage1', models.FileField(blank=True, null=True, upload_to='vendorproductimage')),
                ('addImage2', models.FileField(blank=True, null=True, upload_to='vendorproductimage')),
                ('addImage3', models.FileField(blank=True, null=True, upload_to='vendorproductimage')),
                ('addImage4', models.FileField(blank=True, null=True, upload_to='vendorproductimage')),
                ('uom', models.CharField(blank=True, max_length=100)),
                ('quantity', models.CharField(blank=True, max_length=100)),
                ('hsn_sac', models.CharField(blank=True, max_length=100)),
                ('unit_price', models.CharField(blank=True, max_length=100)),
                ('discount', models.CharField(blank=True, max_length=50)),
                ('tax', models.CharField(blank=True, max_length=100)),
                ('sku_id', models.CharField(blank=True, max_length=100)),
                ('country_of_origin', models.CharField(blank=True, max_length=50)),
                ('currency', models.CharField(blank=True, max_length=50)),
                ('pandf_charges', models.CharField(blank=True, max_length=100)),
                ('fright_charges', models.CharField(blank=True, max_length=100)),
                ('warrenty_or_guarantee', models.CharField(blank=True, max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField()),
            ],
            options={
                'db_table': 'VendorProductsDetail',
            },
        ),
    ]
