# Generated by Django 3.2 on 2021-06-21 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0002_vendorproductsdetail_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorproductsdetail',
            name='type_of_product',
        ),
    ]
