# Generated by Django 3.2 on 2021-07-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorproduct_basicdetails',
            name='add_image1',
            field=models.FileField(blank=True, null=True, upload_to='static/vendorproductimage'),
        ),
    ]
