# Generated by Django 3.2 on 2021-07-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0003_alter_vendorproduct_basicdetails_add_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorproduct_basicdetails',
            name='add_image1',
            field=models.FileField(blank=True, null=True, upload_to='vendorproductimage'),
        ),
    ]
