# Generated by Django 3.2 on 2021-08-06 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0004_auto_20210806_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalvendorproduct_basicdetails',
            name='alternative_parts_no',
        ),
        migrations.RemoveField(
            model_name='historicalvendorproduct_basicdetails',
            name='model_no',
        ),
        migrations.RemoveField(
            model_name='historicalvendorproduct_basicdetails',
            name='part_no',
        ),
        migrations.RemoveField(
            model_name='historicalvendorproduct_generaldetails',
            name='item_weight',
        ),
        migrations.RemoveField(
            model_name='historicalvendorproduct_generaldetails',
            name='packed_weight',
        ),
        migrations.RemoveField(
            model_name='historicalvendorproduct_generaldetails',
            name='product_height',
        ),
        migrations.RemoveField(
            model_name='historicalvendorproduct_generaldetails',
            name='product_length',
        ),
        migrations.RemoveField(
            model_name='historicalvendorproduct_generaldetails',
            name='product_width',
        ),
        migrations.RemoveField(
            model_name='historicalvendorproduct_generaldetails',
            name='ship_via',
        ),
        migrations.RemoveField(
            model_name='historicalvendorproduct_generaldetails',
            name='shipping_uom',
        ),
        migrations.RemoveField(
            model_name='historicalvendorproduct_generaldetails',
            name='shipping_weight',
        ),
        migrations.RemoveField(
            model_name='historicalvendorproduct_generaldetails',
            name='standard_measures',
        ),
        migrations.RemoveField(
            model_name='vendorproduct_basicdetails',
            name='alternative_parts_no',
        ),
        migrations.RemoveField(
            model_name='vendorproduct_basicdetails',
            name='model_no',
        ),
        migrations.RemoveField(
            model_name='vendorproduct_basicdetails',
            name='part_no',
        ),
        migrations.RemoveField(
            model_name='vendorproduct_generaldetails',
            name='item_weight',
        ),
        migrations.RemoveField(
            model_name='vendorproduct_generaldetails',
            name='packed_weight',
        ),
        migrations.RemoveField(
            model_name='vendorproduct_generaldetails',
            name='product_height',
        ),
        migrations.RemoveField(
            model_name='vendorproduct_generaldetails',
            name='product_length',
        ),
        migrations.RemoveField(
            model_name='vendorproduct_generaldetails',
            name='product_width',
        ),
        migrations.RemoveField(
            model_name='vendorproduct_generaldetails',
            name='ship_via',
        ),
        migrations.RemoveField(
            model_name='vendorproduct_generaldetails',
            name='shipping_uom',
        ),
        migrations.RemoveField(
            model_name='vendorproduct_generaldetails',
            name='shipping_weight',
        ),
        migrations.RemoveField(
            model_name='vendorproduct_generaldetails',
            name='standard_measures',
        ),
    ]
