# Generated by Django 3.2 on 2021-06-25 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MaterialApp', '0004_industrialdetails_searchcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProduct_BasicDetails',
            fields=[
                ('vendor_product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('core_sector', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('sub_category', models.CharField(blank=True, max_length=100)),
                ('product_category', models.CharField(blank=True, max_length=100)),
                ('item_type', models.CharField(max_length=100, null=True)),
                ('item_code', models.CharField(max_length=100, null=True, unique=True)),
                ('item_name', models.CharField(max_length=100, null=True)),
                ('final_selling_price', models.CharField(max_length=80, null=True)),
                ('numeric', models.BigIntegerField(null=True)),
                ('add_image1', models.FileField(blank=True, null=True, upload_to='vendorproductimage')),
                ('add_image2', models.FileField(blank=True, null=True, upload_to='vendorproductimage')),
                ('add_image3', models.FileField(blank=True, null=True, upload_to='vendorproductimage')),
                ('add_image4', models.FileField(blank=True, null=True, upload_to='vendorproductimage')),
                ('uom', models.CharField(blank=True, max_length=100)),
                ('quantity', models.CharField(blank=True, max_length=100)),
                ('hsn_sac', models.CharField(blank=True, max_length=100)),
                ('unit_price', models.CharField(blank=True, max_length=100)),
                ('discount', models.CharField(blank=True, max_length=50)),
                ('tax', models.CharField(blank=True, max_length=100)),
                ('sku_id', models.CharField(blank=True, max_length=100)),
                ('country_of_origin', models.CharField(blank=True, max_length=50)),
                ('currency', models.CharField(blank=True, max_length=50)),
                ('pricing', models.CharField(blank=True, max_length=300, null=True)),
                ('request_on_quote', models.CharField(blank=True, max_length=400, null=True)),
                ('price_range', models.CharField(blank=True, max_length=200, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField()),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'VendorProduct_BasicDetails',
            },
        ),
        migrations.CreateModel(
            name='VendorProduct_Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to='vendorproductimage')),
                ('document_description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField()),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor_products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MaterialApp.vendorproduct_basicdetails')),
            ],
            options={
                'db_table': 'VendorProduct_Documents',
            },
        ),
        migrations.CreateModel(
            name='VendorProduct_GeneralDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_f_charges', models.CharField(blank=True, max_length=400, null=True)),
                ('frieght_charges', models.CharField(blank=True, max_length=400, null=True)),
                ('delivery', models.CharField(blank=True, max_length=400, null=True)),
                ('warranty', models.CharField(blank=True, max_length=400)),
                ('brand_make', models.CharField(blank=True, max_length=400)),
                ('department', models.CharField(blank=True, max_length=400)),
                ('guarantee', models.CharField(blank=True, max_length=400)),
                ('model_no', models.CharField(blank=True, max_length=400)),
                ('min_order_quantity', models.CharField(blank=True, max_length=400)),
                ('after_sale_service', models.CharField(blank=True, max_length=400)),
                ('part_no', models.CharField(blank=True, max_length=100)),
                ('packing_type', models.CharField(blank=True, max_length=400)),
                ('not_covered_w_g', models.CharField(blank=True, max_length=400)),
                ('alternate_parts', models.CharField(blank=True, max_length=100)),
                ('delievery_days', models.CharField(blank=True, max_length=100)),
                ('standard_measures', models.CharField(blank=True, max_length=100)),
                ('product_length', models.CharField(blank=True, max_length=100)),
                ('shipping_uom', models.CharField(blank=True, max_length=100)),
                ('item_weight', models.CharField(blank=True, max_length=100)),
                ('product_width', models.CharField(blank=True, max_length=100)),
                ('shipping_weight', models.CharField(blank=True, max_length=100)),
                ('after_packed_weight', models.CharField(blank=True, max_length=100)),
                ('product_height', models.CharField(blank=True, max_length=100)),
                ('ship_via', models.CharField(blank=True, max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField()),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor_products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MaterialApp.vendorproduct_basicdetails')),
            ],
            options={
                'db_table': 'VendorProduct_GeneralDetails',
            },
        ),
        migrations.CreateModel(
            name='VendorProduct_ProductFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_specification', models.CharField(blank=True, max_length=100)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField()),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor_products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MaterialApp.vendorproduct_basicdetails')),
            ],
            options={
                'db_table': 'VendorProduct_ProductFeatures',
            },
        ),
        migrations.CreateModel(
            name='VendorProduct_TechnicalSpecifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_specification', models.CharField(blank=True, max_length=100)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField()),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor_products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MaterialApp.vendorproduct_basicdetails')),
            ],
            options={
                'db_table': 'VendorProduct_TechnicalSpecifications',
            },
        ),
        migrations.RemoveField(
            model_name='vendorproductsdetail',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='IndustrialDetails_SearchCategory',
        ),
        migrations.DeleteModel(
            name='VendorProductsDetail',
        ),
    ]
