# Generated by Django 3.2 on 2021-08-07 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0005_auto_20210806_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalvendorproduct_generaldetails',
            name='min_order_quantity',
        ),
        migrations.RemoveField(
            model_name='vendorproduct_generaldetails',
            name='min_order_quantity',
        ),
    ]
