# Generated by Django 3.2 on 2021-06-25 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0005_auto_20210625_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorproduct_productfeatures',
            old_name='item_description',
            new_name='product_item_description',
        ),
        migrations.RenameField(
            model_name='vendorproduct_productfeatures',
            old_name='item_specification',
            new_name='product_item_specification',
        ),
    ]
