# Generated by Django 3.2 on 2021-06-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0007_historicalvendorproduct_basicdetails_historicalvendorproduct_documents_historicalvendorproduct_gener'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalvendorproduct_basicdetails',
            name='price_range',
        ),
        migrations.RemoveField(
            model_name='historicalvendorproduct_basicdetails',
            name='pricing',
        ),
        migrations.RemoveField(
            model_name='historicalvendorproduct_basicdetails',
            name='request_on_quote',
        ),
        migrations.RemoveField(
            model_name='vendorproduct_basicdetails',
            name='price_range',
        ),
        migrations.RemoveField(
            model_name='vendorproduct_basicdetails',
            name='pricing',
        ),
        migrations.RemoveField(
            model_name='vendorproduct_basicdetails',
            name='request_on_quote',
        ),
        migrations.AddField(
            model_name='historicalvendorproduct_basicdetails',
            name='item_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historicalvendorproduct_basicdetails',
            name='product_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendorproduct_basicdetails',
            name='item_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vendorproduct_basicdetails',
            name='product_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
