# Generated by Django 3.2 on 2021-08-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0007_auto_20210807_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalvendorproduct_productfeatures',
            name='description',
        ),
        migrations.RemoveField(
            model_name='historicalvendorproduct_technicalspecifications',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vendorproduct_productfeatures',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vendorproduct_technicalspecifications',
            name='description',
        ),
    ]
