# Generated by Django 3.2 on 2021-08-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0008_auto_20210807_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvendorproduct_basicdetails',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendorproduct_basicdetails',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=200, null=True),
        ),
    ]
