# Generated by Django 3.2 on 2021-07-02 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MaterialApp', '0008_auto_20210629_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBuyerProductDetails',
            fields=[
                ('buyer_product_id', models.BigIntegerField(blank=True, db_index=True)),
                ('buyer_item_type', models.CharField(max_length=100, null=True)),
                ('buyer_item_code', models.CharField(db_index=True, max_length=100, null=True)),
                ('buyer_item_name', models.CharField(max_length=100, null=True)),
                ('buyer_item_description', models.TextField(null=True)),
                ('buyer_numeric', models.BigIntegerField(null=True)),
                ('buyer_uom', models.CharField(blank=True, max_length=100)),
                ('buyer_hsn_sac', models.CharField(blank=True, max_length=100)),
                ('buyer_unit_price', models.CharField(blank=True, max_length=100)),
                ('buyer_currency', models.CharField(blank=True, max_length=50)),
                ('buyer_country_of_origin', models.CharField(blank=True, max_length=50)),
                ('buyer_category', models.CharField(max_length=500, null=True)),
                ('buyer_department', models.CharField(blank=True, max_length=400, null=True)),
                ('buyer_item_group', models.CharField(blank=True, max_length=500)),
                ('buyer_annual_consumption', models.CharField(blank=True, max_length=500)),
                ('buyer_safety_stock', models.CharField(blank=True, max_length=100)),
                ('buyer_model_no', models.CharField(blank=True, max_length=500)),
                ('buyer_document', models.TextField(blank=True, max_length=100, null=True)),
                ('buyer_additional_specifications', models.TextField(blank=True, null=True)),
                ('buyer_add_product_supplies', models.CharField(blank=True, max_length=200, null=True)),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('updated_on', models.DateTimeField(blank=True, editable=False)),
                ('created_by', models.BigIntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical buyer product details',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BuyerProductDetails',
            fields=[
                ('buyer_product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('buyer_item_type', models.CharField(max_length=100, null=True)),
                ('buyer_item_code', models.CharField(max_length=100, null=True, unique=True)),
                ('buyer_item_name', models.CharField(max_length=100, null=True)),
                ('buyer_item_description', models.TextField(null=True)),
                ('buyer_numeric', models.BigIntegerField(null=True)),
                ('buyer_uom', models.CharField(blank=True, max_length=100)),
                ('buyer_hsn_sac', models.CharField(blank=True, max_length=100)),
                ('buyer_unit_price', models.CharField(blank=True, max_length=100)),
                ('buyer_currency', models.CharField(blank=True, max_length=50)),
                ('buyer_country_of_origin', models.CharField(blank=True, max_length=50)),
                ('buyer_category', models.CharField(max_length=500, null=True)),
                ('buyer_department', models.CharField(blank=True, max_length=400, null=True)),
                ('buyer_item_group', models.CharField(blank=True, max_length=500)),
                ('buyer_annual_consumption', models.CharField(blank=True, max_length=500)),
                ('buyer_safety_stock', models.CharField(blank=True, max_length=100)),
                ('buyer_model_no', models.CharField(blank=True, max_length=500)),
                ('buyer_document', models.FileField(blank=True, null=True, upload_to='BuyerProductFiles')),
                ('buyer_additional_specifications', models.TextField(blank=True, null=True)),
                ('buyer_add_product_supplies', models.CharField(blank=True, max_length=200, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField()),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'BuyerProductDetails',
            },
        ),
    ]
