# Generated by Django 3.2 on 2021-07-06 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0009_buyerproductdetails_historicalbuyerproductdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerproductdetails',
            name='buyer_country_of_origin',
        ),
        migrations.RemoveField(
            model_name='buyerproductdetails',
            name='buyer_currency',
        ),
        migrations.RemoveField(
            model_name='historicalbuyerproductdetails',
            name='buyer_country_of_origin',
        ),
        migrations.RemoveField(
            model_name='historicalbuyerproductdetails',
            name='buyer_currency',
        ),
    ]
