# Generated by Django 3.2 on 2021-08-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0009_auto_20210807_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalvendorproduct_documents',
            old_name='document',
            new_name='document1',
        ),
        migrations.RenameField(
            model_name='historicalvendorproduct_documents',
            old_name='document_description',
            new_name='document_description1',
        ),
        migrations.RenameField(
            model_name='vendorproduct_documents',
            old_name='document',
            new_name='document1',
        ),
        migrations.RenameField(
            model_name='vendorproduct_documents',
            old_name='document_description',
            new_name='document_description1',
        ),
        migrations.AddField(
            model_name='historicalvendorproduct_documents',
            name='document2',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalvendorproduct_documents',
            name='document3',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalvendorproduct_documents',
            name='document_description2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalvendorproduct_documents',
            name='document_description3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorproduct_documents',
            name='document2',
            field=models.FileField(blank=True, null=True, upload_to='vendorproductimage'),
        ),
        migrations.AddField(
            model_name='vendorproduct_documents',
            name='document3',
            field=models.FileField(blank=True, null=True, upload_to='vendorproductimage'),
        ),
        migrations.AddField(
            model_name='vendorproduct_documents',
            name='document_description2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorproduct_documents',
            name='document_description3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
