# Generated by Django 3.2 on 2021-08-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0010_auto_20210807_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvendorproduct_basicdetails',
            name='item_code_manual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorproduct_basicdetails',
            name='item_code_manual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
