# Generated by Django 3.2 on 2021-07-06 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MaterialApp', '0010_auto_20210706_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerproductdetails',
            name='code_format',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='historicalbuyerproductdetails',
            name='code_format',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.CreateModel(
            name='ItemCodeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=200)),
                ('prefix', models.CharField(blank=True, max_length=70, null=True)),
                ('numeric', models.CharField(max_length=30)),
                ('suffix', models.CharField(blank=True, max_length=70, null=True)),
                ('code_format', models.CharField(blank=True, max_length=120, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField()),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ItemCodeSettings',
            },
        ),
    ]
