# Generated by Django 3.2 on 2021-07-06 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0011_auto_20210706_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerproductdetails',
            name='code_format',
        ),
        migrations.RemoveField(
            model_name='historicalbuyerproductdetails',
            name='code_format',
        ),
    ]
