# Generated by Django 3.2 on 2021-08-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0011_auto_20210808_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvendorproduct_basicdetails',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorproduct_basicdetails',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
