# Generated by Django 3.2 on 2021-08-13 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0012_auto_20210813_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalvendorproduct_basicdetails',
            old_name='vendor_code',
            new_name='company_code',
        ),
        migrations.RenameField(
            model_name='vendorproduct_basicdetails',
            old_name='vendor_code',
            new_name='company_code',
        ),
    ]
