# Generated by Django 3.2 on 2021-07-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0012_auto_20210706_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerproductdetails',
            name='buyer_product_status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalbuyerproductdetails',
            name='buyer_product_status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
