# Generated by Django 3.2 on 2021-08-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0015_auto_20210820_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcodesettings',
            name='numeric',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
