# Generated by Django 3.2 on 2021-09-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0018_auto_20210904_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagebidding',
            name='item_type',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
