# Generated by Django 3.2 on 2021-09-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0019_landingpagebidding_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagebidding',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagebidding',
            name='vendor_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
