# Generated by Django 3.2 on 2021-09-09 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MaterialApp', '0020_auto_20210909_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageBidding_Publish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=500, null=True)),
                ('company_code', models.CharField(blank=True, max_length=100, null=True)),
                ('priority', models.CharField(blank=True, max_length=150, null=True)),
                ('deadline_date', models.CharField(blank=True, max_length=120, null=True)),
                ('item_name', models.CharField(blank=True, max_length=150, null=True)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('uom', models.CharField(blank=True, max_length=70, null=True)),
                ('quantity', models.CharField(blank=True, max_length=200, null=True)),
                ('hsn_sac', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=300, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='LandingPageBiddingFiles')),
                ('unit_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('tax', models.CharField(blank=True, max_length=50, null=True)),
                ('discount', models.CharField(blank=True, max_length=50, null=True)),
                ('total_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('pf_charges', models.CharField(blank=True, max_length=400, null=True)),
                ('frieght_charges', models.CharField(blank=True, max_length=400, null=True)),
                ('delivery_charges', models.CharField(blank=True, max_length=400, null=True)),
                ('listing_user_id', models.CharField(max_length=40)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField()),
                ('publish_status', models.CharField(default='Published', max_length=150)),
                ('listing_leads', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MaterialApp.landingpagebidding')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'LandingPageBidding_Publish',
            },
        ),
    ]
