# Generated by Django 3.2 on 2021-09-09 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0021_landingpagebidding_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpagebidding_publish',
            name='document',
        ),
        migrations.RemoveField(
            model_name='landingpagebidding_publish',
            name='listing_user_id',
        ),
    ]
