# Generated by Django 3.2 on 2021-09-09 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0022_auto_20210909_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landingpagebidding_publish',
            old_name='frieght_charges',
            new_name='payment_charges',
        ),
    ]
