# Generated by Django 3.1.5 on 2021-09-20 09:44

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0023_rename_frieght_charges_landingpagebidding_publish_payment_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvendorproduct_documents',
            name='id',
            field=models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalvendorproduct_generaldetails',
            name='id',
            field=models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalvendorproduct_productfeatures',
            name='id',
            field=models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalvendorproduct_technicalspecifications',
            name='id',
            field=models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='itemcodesettings',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='landingpagebidding',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='landingpagebidding_publish',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vendorproduct_documents',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vendorproduct_generaldetails',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vendorproduct_productfeatures',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vendorproduct_technicalspecifications',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='awardpostedRFQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemType', models.CharField(blank=True, max_length=100, null=True)),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('priority', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_publish_date', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_deadLine_date', models.CharField(blank=True, max_length=100, null=True)),
                ('Buyer_delivery_Terms', models.CharField(blank=True, max_length=100, null=True)),
                ('Buyer_pfcharges_Terms', models.CharField(blank=True, max_length=100, null=True)),
                ('Buyer_payment_Terms', models.CharField(blank=True, max_length=100, null=True)),
                ('landing_page_bidding_publish_id', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), size=None)),
                ('landingpage_bidding_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MaterialApp.landingpagebidding')),
            ],
            options={
                'db_table': 'AwardpostedRFQBuyer',
            },
        ),
    ]
