# Generated by Django 3.1.5 on 2021-09-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0025_auto_20210920_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardpostedrfq',
            name='po_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
