# Generated by Django 3.2 on 2021-09-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0028_auto_20210923_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpagebidding',
            name='priority',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
