# Generated by Django 3.2 on 2021-10-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0029_alter_landingpagebidding_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyermachinarydetails',
            name='buyer_machinary_document_1',
            field=models.FileField(blank=True, null=True, upload_to='BuyerMachinaryFiles'),
        ),
        migrations.AddField(
            model_name='buyermachinarydetails',
            name='buyer_machinary_document_2',
            field=models.FileField(blank=True, null=True, upload_to='BuyerMachinaryFiles'),
        ),
        migrations.AddField(
            model_name='buyerproductdetails',
            name='buyer_document_1',
            field=models.FileField(blank=True, null=True, upload_to='BuyerProductFiles'),
        ),
        migrations.AddField(
            model_name='buyerproductdetails',
            name='buyer_document_2',
            field=models.FileField(blank=True, null=True, upload_to='BuyerProductFiles'),
        ),
        migrations.AddField(
            model_name='buyerservicedetails',
            name='buyer_service_document_1',
            field=models.FileField(blank=True, null=True, upload_to='BuyerProductFiles'),
        ),
        migrations.AddField(
            model_name='buyerservicedetails',
            name='buyer_service_document_2',
            field=models.FileField(blank=True, null=True, upload_to='BuyerProductFiles'),
        ),
        migrations.AddField(
            model_name='historicalbuyermachinarydetails',
            name='buyer_machinary_document_1',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalbuyermachinarydetails',
            name='buyer_machinary_document_2',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalbuyerproductdetails',
            name='buyer_document_1',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalbuyerproductdetails',
            name='buyer_document_2',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalbuyerservicedetails',
            name='buyer_service_document_1',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalbuyerservicedetails',
            name='buyer_service_document_2',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
