# Generated by Django 3.2 on 2021-10-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0030_auto_20211006_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardpostedrfq',
            name='awarded_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
