# Generated by Django 3.2 on 2021-10-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0031_awardpostedrfq_awarded_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardpostedrfq',
            name='awarded_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
