# Generated by Django 3.2 on 2021-11-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0034_auto_20211016_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvendorproduct_generaldetails',
            name='available_stock',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvendorproduct_generaldetails',
            name='not_covered_w_g',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='vendorproduct_generaldetails',
            name='available_stock',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendorproduct_generaldetails',
            name='not_covered_w_g',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
