# Generated by Django 3.2.3 on 2021-11-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0035_auto_20211103_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyermachinarydetails',
            name='custom_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='buyerproductdetails',
            name='custom_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='buyerservicedetails',
            name='custom_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalbuyermachinarydetails',
            name='custom_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalbuyerproductdetails',
            name='custom_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalbuyerservicedetails',
            name='custom_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
