# Generated by Django 3.2.3 on 2021-11-15 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0037_historicallandingpagelistingleadspurchaseorder_landingpagelistingleadspurchaseorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalLandingPageListingLeadsPurchaseOrder',
        ),
    ]
