# Generated by Django 3.2.3 on 2021-11-15 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0038_delete_historicallandingpagelistingleadspurchaseorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpagelistingleadspurchaseorder',
            name='rfq_number',
        ),
        migrations.RemoveField(
            model_name='landingpagelistingleadspurchaseorder',
            name='rfq_title',
        ),
    ]
