# Generated by Django 3.2.3 on 2021-11-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0040_auto_20211115_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagelistingleadspurchaseorder',
            name='item_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpagelistingleadspurchaseorder',
            name='item_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
