# Generated by Django 3.2.3 on 2021-11-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0041_auto_20211116_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagelistingleadspurchaseorder',
            name='item_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
