# Generated by Django 3.2.9 on 2022-01-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0044_auto_20211230_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvendorproduct_basicdetails',
            name='admin_create',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalvendorproduct_documents',
            name='admin_create',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalvendorproduct_generaldetails',
            name='admin_create',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalvendorproduct_productfeatures',
            name='admin_create',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalvendorproduct_technicalspecifications',
            name='admin_create',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='vendorproduct_basicdetails',
            name='admin_create',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='vendorproduct_documents',
            name='admin_create',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='vendorproduct_generaldetails',
            name='admin_create',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='vendorproduct_productfeatures',
            name='admin_create',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='vendorproduct_technicalspecifications',
            name='admin_create',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
