# Generated by Django 3.2.9 on 2022-02-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0045_auto_20220103_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagelistingleadspurchaseorder',
            name='awarded_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpagelistingleadspurchaseorder',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='landingpagelistingleadspurchaseorder',
            name='discount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='landingpagelistingleadspurchaseorder',
            name='quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='landingpagelistingleadspurchaseorder',
            name='tax',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='landingpagelistingleadspurchaseorder',
            name='total_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='landingpagelistingleadspurchaseorder',
            name='unit_rate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='landingpagelistingleadspurchaseorder',
            name='uom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
