# Generated by Django 3.2.9 on 2022-02-16 12:38

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MaterialApp', '0046_auto_20220211_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProduct_Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(blank=True, max_length=600, null=True)),
                ('data_type', models.CharField(blank=True, max_length=700, null=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('default_value', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('text_box_with_dropdown', models.BooleanField(default=False)),
                ('number_with_dropdown', models.BooleanField(default=False)),
                ('textbox_w_dropdown_text_value', models.CharField(blank=True, max_length=800, null=True)),
                ('textbox_w_dropdown_dropdown_value', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('number_with_dropdown_num_value', models.FloatField(blank=True, null=True)),
                ('number_wih_dropdown_dropdown_value', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField()),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor_products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MaterialApp.vendorproduct_basicdetails')),
            ],
            options={
                'db_table': 'VendorProduct_Requirements',
            },
        ),
    ]
