# Generated by Django 3.2.9 on 2022-02-21 14:11

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MaterialApp', '0047_vendorproduct_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerProduct_Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_label_name', models.CharField(blank=True, max_length=600, null=True)),
                ('buyer_radio_button', models.CharField(blank=True, max_length=200, null=True)),
                ('buyer_single_selection_check', models.CharField(blank=True, max_length=200, null=True)),
                ('buyer_multiple_selection_check', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('buyer_text_area', models.TextField(blank=True, null=True)),
                ('buyer_number_type', models.FloatField(blank=True, null=True)),
                ('buyer_textbox_with_dropdown', models.CharField(blank=True, max_length=800, null=True)),
                ('buyer_number_with_dropdown', models.FloatField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField()),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'BuyerProduct_Requirements',
            },
        ),
    ]
