# Generated by Django 3.2.9 on 2022-02-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0048_buyerproduct_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerproduct_requirements',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
