# Generated by Django 3.2.9 on 2022-02-21 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0049_buyerproduct_requirements_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyerproduct_requirements',
            old_name='buyer_multiple_selection_check',
            new_name='buyer_default_value',
        ),
        migrations.RemoveField(
            model_name='buyerproduct_requirements',
            name='buyer_radio_button',
        ),
        migrations.RemoveField(
            model_name='buyerproduct_requirements',
            name='buyer_single_selection_check',
        ),
        migrations.RemoveField(
            model_name='buyerproduct_requirements',
            name='product_name',
        ),
        migrations.AddField(
            model_name='buyerproduct_requirements',
            name='buyer_data_type',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='buyerproduct_requirements',
            name='vendor_product_basic_pk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MaterialApp.vendorproduct_basicdetails'),
        ),
        migrations.AddField(
            model_name='buyerproduct_requirements',
            name='vendor_product_requirement_pk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MaterialApp.vendorproduct_requirements'),
        ),
    ]
