# Generated by Django 3.2.9 on 2022-02-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0050_auto_20220221_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerproduct_requirements',
            name='buyer_number_type',
        ),
        migrations.RemoveField(
            model_name='buyerproduct_requirements',
            name='buyer_number_with_dropdown',
        ),
        migrations.RemoveField(
            model_name='buyerproduct_requirements',
            name='buyer_text_area',
        ),
        migrations.RemoveField(
            model_name='buyerproduct_requirements',
            name='buyer_textbox_with_dropdown',
        ),
        migrations.AddField(
            model_name='buyerproduct_requirements',
            name='is_mandatory',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
