# Generated by Django 3.2.9 on 2022-03-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0052_auto_20220308_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerproduct_requirements',
            name='landing_page_pk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
