# Generated by Django 3.2.9 on 2022-03-09 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialApp', '0053_alter_buyerproduct_requirements_landing_page_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpagebidding',
            name='buyer_requirement_pk',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='MaterialApp.buyerproduct_requirements'),
        ),
    ]
