"""
Django settings for Vendorsinprojectversion2 project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os.path
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# ------

BASE_DIR = Path("/home/bvendorsinprod/actions-runner/_work/media/").resolve().parent.parent
# ----

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6jn&@g4bzf##va8#0$bh9p-z@!nc^33v5syykn_ib6q96p@1my'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'rest_framework',
    'corsheaders',
    'RegistrationApp',
    'MastersApp',
    'MaterialApp',
    'LandingPageApp',
    'rest_framework.authtoken',
    'AdminApp',
    'DashboardApp',
    'BiddingApp',
    'SubscriptionApp'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'LandingPageApp.middleware.ActiveUserMiddleware',
]

ROOT_URLCONF = 'Vendorsinprojectversion2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Vendorsinprojectversion2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'ProductionServer',
        'USER': 'vendorsincommerce@vendorsincommerce',
        'PASSWORD':'Vendorsin@vsin2021',
        'HOST': 'vendorsincommerce.postgres.database.azure.com',
        'PORT': '5432',
        'sslrequire':True,
    }

}

# Development convenience: use SQLite when the environment variable is set
# (e.g. in local containers where the production database isn't reachable).
#
# To launch the app without altering the real DATABASES block above, start the
# server with ``USE_SQLITE=1``.  The file ``db.sqlite3`` will live in
# ``BASE_DIR``.
# define a boolean to let other code (including migrations) know we're in
# sqlite mode; migrations have been patched to consult this setting.
USE_SQLITE = DEBUG and os.environ.get('USE_SQLITE') == '1'

if USE_SQLITE:
    # use a database file inside the workspace so the container user can write
    sqlite_path = os.path.join(os.getcwd(), 'db.sqlite3')
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': sqlite_path,
        }
    }

    # When running on SQLite, postgres.ArrayField is not supported by the SQL
    # dialect.  During migrations we still import ArrayField but its
    # ``db_type()`` must produce something SQLite accepts.  Monkey-patch the
    # class so all existing migrations automatically use TEXT instead of
    # ``varchar(… )[]``.  This saves us from editing dozens of files.
    try:
        from django.contrib.postgres.fields import ArrayField
        def _sqlite_array_db_type(self, connection):
            # ignore base_field, always create a generic text column
            return 'text'
        ArrayField.db_type = _sqlite_array_db_type
    except ImportError:
        pass

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES':[
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PERMISSION_CLASSES':[
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ]
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

AUTH_USER_MODEL ='RegistrationApp.SelfRegistration'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CORS_ORIGIN_ALLOW_ALL = True


# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
#         'LOCATION': '127.0.0.1:11211',
#     }
# }

# Number of seconds of inactivity before a user is marked offline
USER_ONLINE_TIMEOUT = 300

# Number of seconds that we will keep track of inactive users for before
# their last seen is removed from the cache
USER_LASTSEEN_TIMEOUT = 60 * 60 * 24 * 7


