# Generated by Django 3.2 on 2021-08-03 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_type', models.CharField(max_length=100)),
                ('invite_date', models.CharField(max_length=50)),
                ('register_date', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=100, unique=True)),
                ('user_add_to', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=100)),
            ],
            options={
                'db_table': 'AdminInvite',
            },
        ),
        migrations.CreateModel(
            name='AdminRegister',
            fields=[
                ('admin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=70)),
                ('company_name', models.CharField(max_length=100)),
                ('admin_email', models.CharField(max_length=150, unique=True)),
                ('admin_phone', models.CharField(max_length=15, unique=True)),
                ('email_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('phone_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('password', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'AdminRegister',
            },
        ),
        migrations.CreateModel(
            name='CreateUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(max_length=30, unique=True)),
                ('numeric', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('user_type', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('working_location', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('land_mark', models.CharField(blank=True, max_length=200, null=True)),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
                ('business_unit', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=20)),
                ('company_unit', models.CharField(max_length=100)),
                ('company_code', models.CharField(max_length=20)),
                ('reporting_manager', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('alternate_email', models.CharField(blank=True, max_length=30, null=True)),
                ('alternate_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=30, null=True)),
                ('pan_number', models.CharField(max_length=20, unique=True)),
                ('aadhar_number', models.CharField(max_length=20, unique=True)),
                ('relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('driving_license', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('passport', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('any_other', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(default='Active', max_length=50)),
            ],
            options={
                'db_table': 'CreateUser',
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modules', models.CharField(max_length=400, unique=True)),
                ('full_access', models.BooleanField(blank=True, null=True)),
                ('read', models.BooleanField(blank=True, null=True)),
                ('create', models.BooleanField(blank=True, null=True)),
                ('modify', models.BooleanField(blank=True, null=True)),
                ('delete', models.BooleanField(blank=True, null=True)),
                ('disable', models.BooleanField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('admins', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister')),
            ],
            options={
                'db_table': 'Permissions',
            },
        ),
    ]
