# Generated by Django 3.2.3 on 2021-05-27 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createuser',
            old_name='adhar_number',
            new_name='aadhar_number',
        ),
        migrations.RenameField(
            model_name='historicalcreateuser',
            old_name='adhar_number',
            new_name='aadhar_number',
        ),
        migrations.AddField(
            model_name='admininvite',
            name='admins',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admininvite',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='admininvite',
            name='register_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='admininvite',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='createuser',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='createuser',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.admininvite'),
        ),
        migrations.AddField(
            model_name='createuser',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaladmininvite',
            name='admins',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AdminApp.adminregister'),
        ),
        migrations.AddField(
            model_name='historicaladmininvite',
            name='created_on',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicaladmininvite',
            name='register_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicaladmininvite',
            name='updated_on',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalcreateuser',
            name='created_on',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalcreateuser',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AdminApp.admininvite'),
        ),
        migrations.AddField(
            model_name='historicalcreateuser',
            name='updated_on',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='permissions',
            name='admins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister'),
        ),
        migrations.AddField(
            model_name='permissions',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='permissions',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permissions',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='admininvite',
            name='invite_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='createuser',
            name='user_code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='historicaladmininvite',
            name='invite_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalcreateuser',
            name='user_code',
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
