# Generated by Django 3.2 on 2021-06-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createuser',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalcreateuser',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
