# Generated by Django 3.2.3 on 2021-05-27 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_auto_20210527_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createuser',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='historicalcreateuser',
            name='updated_by',
        ),
    ]
