# Generated by Django 3.2 on 2021-07-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_imagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image_1',
            field=models.BinaryField(editable=True),
        ),
    ]
