# Generated by Django 3.2 on 2021-06-07 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_auto_20210605_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createuser',
            old_name='grander',
            new_name='working_location',
        ),
        migrations.RenameField(
            model_name='historicalcreateuser',
            old_name='grander',
            new_name='working_location',
        ),
        migrations.AddField(
            model_name='createuser',
            name='admins',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcreateuser',
            name='admins',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AdminApp.adminregister'),
        ),
    ]
