# Generated by Django 3.2 on 2021-07-05 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_alter_imagemodel_image_1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
