# Generated by Django 3.2 on 2021-07-28 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_auto_20210727_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcreateuser',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='historicalcreateuser',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalAdminInvite',
        ),
        migrations.DeleteModel(
            name='HistoricalCreateUser',
        ),
    ]
