# Generated by Django 3.2 on 2021-08-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0005_auto_20210809_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createuser',
            name='user_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
