# Generated by Django 3.2 on 2021-08-22 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdminApp', '0008_auto_20210820_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminregister',
            name='super_admin_key',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='createuser',
            name='created_by',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='createuser',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
