# Generated by Django 3.2 on 2021-09-20 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0011_auto_20210904_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateBuyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(max_length=500)),
                ('gst_no', models.CharField(max_length=50)),
                ('company_type', models.CharField(max_length=280)),
                ('currency', models.CharField(max_length=300)),
                ('pan_number', models.CharField(max_length=80)),
                ('tax_payer_type', models.CharField(max_length=150)),
                ('msme_registered', models.CharField(max_length=50)),
                ('established_year', models.CharField(max_length=100)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('industrial_scale', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=250, unique=True)),
                ('phone_no', models.CharField(max_length=30)),
                ('emergency_no', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('alternate_email', models.CharField(max_length=100)),
                ('bill_company_name', models.CharField(max_length=300)),
                ('bill_address', models.TextField()),
                ('bill_city', models.CharField(max_length=400)),
                ('bill_state', models.CharField(max_length=400)),
                ('bill_country', models.CharField(max_length=300)),
                ('bill_pincode', models.IntegerField()),
                ('bill_landmark', models.CharField(blank=True, max_length=600, null=True)),
                ('bill_location', models.CharField(blank=True, max_length=300, null=True)),
                ('ship_company_name', models.CharField(max_length=300)),
                ('ship_address', models.TextField()),
                ('ship_city', models.CharField(max_length=400)),
                ('ship_state', models.CharField(max_length=400)),
                ('ship_country', models.CharField(max_length=300)),
                ('ship_pincode', models.IntegerField()),
                ('ship_landmark', models.CharField(blank=True, max_length=600, null=True)),
                ('ship_location', models.CharField(blank=True, max_length=300, null=True)),
                ('numeric', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('user_image', models.FileField(blank=True, null=True, upload_to='AdminImages')),
                ('admins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister')),
            ],
            options={
                'db_table': 'CreateBuyer',
            },
        ),
    ]
