# Generated by Django 3.2 on 2021-09-20 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0012_createbuyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenLeadsRfq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=200)),
                ('rfq_number', models.CharField(max_length=50)),
                ('rfq_status', models.CharField(max_length=80)),
                ('rfq_type', models.CharField(max_length=80)),
                ('publish_date', models.CharField(max_length=100)),
                ('deadline_date', models.CharField(max_length=100)),
                ('closing_date', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=280)),
                ('currency', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('bill_address', models.TextField()),
                ('ship_address', models.TextField()),
                ('scope_of_supply', models.TextField()),
                ('scope_of_work', models.TextField()),
                ('additional_info', models.TextField()),
                ('document_1', models.FileField(upload_to='OpenLeadsDocuments')),
                ('document_name_1', models.CharField(max_length=500)),
                ('document_2', models.FileField(upload_to='OpenLeadsDocuments')),
                ('document_name_2', models.CharField(max_length=500)),
                ('document_3', models.FileField(upload_to='OpenLeadsDocuments')),
                ('document_name_3', models.CharField(max_length=500)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('admins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister')),
            ],
            options={
                'db_table': 'OpenLeadsRfq',
            },
        ),
        migrations.CreateModel(
            name='OpenLeadsItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=300)),
                ('item_description', models.TextField()),
                ('uom', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('admins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister')),
            ],
            options={
                'db_table': 'OpenLeadsItems',
            },
        ),
    ]
