# Generated by Django 3.2 on 2021-09-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0013_openleadsitems_openleadsrfq'),
    ]

    operations = [
        migrations.AddField(
            model_name='openleadsrfq',
            name='numeric',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openleadsrfq',
            name='rfq_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
