# Generated by Django 3.2 on 2021-09-21 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0013_auto_20210920_1514'),
        ('AdminApp', '0014_auto_20210920_1254'),
    ]

    operations = [
    ]
