# Generated by Django 3.2 on 2021-10-01 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0016_auto_20210923_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenLeadsPublish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('vendor_code', models.CharField(max_length=70)),
                ('nature_of_busines', models.CharField(max_length=200)),
                ('supply_capability', models.CharField(max_length=200)),
                ('vendor_group', models.CharField(blank=True, max_length=200, null=True)),
                ('maincore', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=300)),
                ('sub_category', models.CharField(max_length=300)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('admins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister')),
            ],
            options={
                'db_table': 'OpenLeadsPublish',
            },
        ),
    ]
