# Generated by Django 3.2 on 2021-10-04 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdminApp', '0018_auto_20211004_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBuyerProductDetailsAdmin',
            fields=[
                ('product_id', models.BigIntegerField(blank=True, db_index=True)),
                ('item_type', models.CharField(max_length=100, null=True)),
                ('item_code', models.CharField(db_index=True, max_length=100, null=True)),
                ('item_name', models.CharField(max_length=100, null=True)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('numeric', models.CharField(blank=True, max_length=50, null=True)),
                ('uom', models.CharField(blank=True, max_length=100)),
                ('hsn_sac', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_price', models.CharField(blank=True, max_length=100, null=True)),
                ('prefix', models.CharField(blank=True, max_length=50, null=True)),
                ('suffix', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=500, null=True)),
                ('department', models.CharField(blank=True, max_length=400, null=True)),
                ('item_group', models.CharField(blank=True, max_length=500, null=True)),
                ('annual_consumption', models.CharField(blank=True, max_length=500, null=True)),
                ('safety_stock', models.CharField(blank=True, max_length=100, null=True)),
                ('model_no', models.CharField(blank=True, max_length=500, null=True)),
                ('document1', models.TextField(blank=True, max_length=100, null=True)),
                ('document2', models.TextField(blank=True, max_length=100, null=True)),
                ('document3', models.TextField(blank=True, max_length=100, null=True)),
                ('additional_specifications', models.TextField(blank=True, null=True)),
                ('add_product_supplies', models.CharField(blank=True, max_length=200, null=True)),
                ('product_status', models.CharField(default='Active', max_length=50)),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('updated_on', models.DateTimeField(blank=True, editable=False)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('admins', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AdminApp.adminregister')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical buyer product details admin',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BuyerProductDetailsAdmin',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_type', models.CharField(max_length=100, null=True)),
                ('item_code', models.CharField(max_length=100, null=True, unique=True)),
                ('item_name', models.CharField(max_length=100, null=True)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('numeric', models.CharField(blank=True, max_length=50, null=True)),
                ('uom', models.CharField(blank=True, max_length=100)),
                ('hsn_sac', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_price', models.CharField(blank=True, max_length=100, null=True)),
                ('prefix', models.CharField(blank=True, max_length=50, null=True)),
                ('suffix', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=500, null=True)),
                ('department', models.CharField(blank=True, max_length=400, null=True)),
                ('item_group', models.CharField(blank=True, max_length=500, null=True)),
                ('annual_consumption', models.CharField(blank=True, max_length=500, null=True)),
                ('safety_stock', models.CharField(blank=True, max_length=100, null=True)),
                ('model_no', models.CharField(blank=True, max_length=500, null=True)),
                ('document1', models.FileField(blank=True, null=True, upload_to='BuyerProductFilesAdmin')),
                ('document2', models.FileField(blank=True, null=True, upload_to='BuyerProductFilesAdmin')),
                ('document3', models.FileField(blank=True, null=True, upload_to='BuyerProductFilesAdmin')),
                ('additional_specifications', models.TextField(blank=True, null=True)),
                ('add_product_supplies', models.CharField(blank=True, max_length=200, null=True)),
                ('product_status', models.CharField(default='Active', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('admins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister')),
            ],
            options={
                'db_table': 'BuyerProductDetailsAdmin',
            },
        ),
    ]
