# Generated by Django 3.2 on 2021-10-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0019_buyerproductdetailsadmin_historicalbuyerproductdetailsadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='openleadsitems',
            name='buyer_company_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='openleadspublish',
            name='buyer_company_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='openleadsrfq',
            name='buyer_company_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='openleadsrfq',
            name='maincore',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='openleadsrfq',
            name='subcategory',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='openleadstermsdescription',
            name='buyer_company_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
