# Generated by Django 3.2 on 2021-10-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0020_auto_20211005_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='openleadsitems',
            name='dcouments',
            field=models.FileField(blank=True, default='OpenLeadsItemsFiles', null=True, upload_to=''),
        ),
    ]
