# Generated by Django 3.2 on 2021-10-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0022_auto_20211005_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='openleadsrfq',
            name='rfq_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
