# Generated by Django 3.2 on 2021-10-08 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdminApp', '0023_openleadsrfq_rfq_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenLeadsVendorPublishRfq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_rfq_number', models.CharField(blank=True, max_length=50, null=True)),
                ('vendor_rfq_status', models.CharField(blank=True, max_length=80, null=True)),
                ('vendor_rfq_type', models.CharField(max_length=80)),
                ('buyer_publish_date', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_publish_date', models.DateField(auto_now_add=True)),
                ('vendor_deadline_date', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_closing_date', models.CharField(blank=True, max_length=100, null=True)),
                ('maincore', models.CharField(blank=True, max_length=300, null=True)),
                ('category', models.CharField(blank=True, max_length=250, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=300, null=True)),
                ('vendor_bill_address', models.TextField(blank=True, null=True)),
                ('vendor_ship_address', models.TextField(blank=True, null=True)),
                ('vendor_rfq_title', models.TextField(blank=True, null=True)),
                ('final_amount', models.CharField(blank=True, max_length=200, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('open_rfq_buyer_pk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.openleadsrfq')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'OpenLeadsVendorPublishRfq',
            },
        ),
        migrations.CreateModel(
            name='OpenLeadsVendorPublishTermsDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_rfq_number', models.CharField(blank=True, max_length=200, null=True)),
                ('vendor_terms', models.CharField(blank=True, max_length=500, null=True)),
                ('vendor_description', models.TextField(blank=True, null=True)),
                ('vendor_response', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('vendor_rfq_type', models.CharField(blank=True, max_length=150, null=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor_open_leads_pk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.openleadsvendorpublishrfq')),
            ],
            options={
                'db_table': 'OpenLeadsVendorPublishTermsDescription',
            },
        ),
        migrations.CreateModel(
            name='OpenLeadsVendorPublishItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_item_type', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_item_name', models.CharField(max_length=300)),
                ('vendor_item_description', models.TextField(blank=True, null=True)),
                ('vendor_uom', models.CharField(max_length=100)),
                ('buyer_quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_tax', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_discount', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_total_amount', models.CharField(blank=True, max_length=80, null=True)),
                ('vendor_rfq_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor_open_leads_pk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.openleadsvendorpublishrfq')),
            ],
            options={
                'db_table': 'OpenLeadsVendorPublishItems',
            },
        ),
    ]
