# Generated by Django 3.2 on 2021-10-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0024_openleadsvendorpublishitems_openleadsvendorpublishrfq_openleadsvendorpublishtermsdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openleadsrfq',
            name='rfq_status',
            field=models.CharField(blank=True, default='Pending', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='openleadsvendorpublishrfq',
            name='vendor_rfq_status',
            field=models.CharField(blank=True, default='Pending', max_length=80, null=True),
        ),
    ]
