# Generated by Django 3.2 on 2021-10-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0025_auto_20211008_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='openleadsvendorpublishrfq',
            name='buyer_company_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='openleadsvendorpublishrfq',
            name='buyer_company_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
