# Generated by Django 3.2 on 2021-10-11 12:11

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdminApp', '0026_auto_20211008_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenLeadsAwards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfq_number', models.CharField(max_length=50)),
                ('company_code', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('buyer_bid_quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_bid_quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('totalamount', models.CharField(blank=True, max_length=200, null=True)),
                ('rfq_title', models.CharField(blank=True, max_length=100, null=True)),
                ('rfq_status', models.CharField(blank=True, default='Pending', max_length=100, null=True)),
                ('product_code', models.TextField(blank=True, null=True) if 'sqlite3' in settings.DATABASES['default']['ENGINE'] else django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('product_name', models.TextField(blank=True, null=True) if 'sqlite3' in settings.DATABASES['default']['ENGINE'] else django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('daterange', models.DateField(blank=True, null=True)),
                ('product_description', models.TextField(blank=True, null=True) if 'sqlite3' in settings.DATABASES['default']['ENGINE'] else django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('awarded_date', models.DateField(auto_now=True, null=True)),
                ('publish_date', models.CharField(blank=True, max_length=100, null=True)),
                ('deadline_date', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('postatus', models.CharField(blank=True, default='Pending', max_length=100, null=True)),
                ('rfq_type', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'OpenLeadsAwards',
            },
        ),
    ]
