# Generated by Django 3.2 on 2021-10-11 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0028_auto_20211011_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='openleadsawards',
            name='admins',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister'),
        ),
    ]
