# Generated by Django 3.2 on 2021-10-11 12:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0029_openleadsawards_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openleadsawards',
            name='company_code',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='openleadsawards',
            name='company_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
