# Generated by Django 3.2 on 2021-10-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0031_alter_openleadsawards_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerproductdetailsadmin',
            name='rfq_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalbuyerproductdetailsadmin',
            name='rfq_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='openleadsvendorpublishitems',
            name='vendor_rfq_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
