# Generated by Django 3.2 on 2021-10-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0032_auto_20211012_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openleadsvendorpublishitems',
            name='vendor_rfq_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
