# Generated by Django 3.2 on 2021-10-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0033_alter_openleadsvendorpublishitems_vendor_rfq_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='openleadsitems',
            name='rfq_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
