# Generated by Django 3.2 on 2021-10-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0034_openleadsitems_rfq_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='openleadsvendorpublishitems',
            name='buyer_company_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='openleadsvendorpublishitems',
            name='buyer_company_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='openleadsvendorpublishtermsdescription',
            name='buyer_company_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='openleadsvendorpublishtermsdescription',
            name='buyer_company_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
