# Generated by Django 3.2 on 2021-10-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0035_auto_20211012_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='openleadsvendorpublishitems',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='openleadsvendorpublishrfq',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='openleadsvendorpublishtermsdescription',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.DeleteModel(
            name='OpenLeadsPublish',
        ),
    ]
