# Generated by Django 3.2 on 2021-10-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0036_auto_20211012_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openleadstermsdescription',
            name='rfq_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
