# Generated by Django 3.2.3 on 2021-11-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0038_alter_openleadstermsdescription_rfq_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='openleadsvendorpublishrfq',
            name='vendor_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
