# Generated by Django 3.2.9 on 2021-12-08 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0039_openleadsvendorpublishrfq_vendor_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSelectedCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=200, null=True)),
                ('category_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('category_image', models.FileField(blank=True, null=True, upload_to='CategoryImage')),
                ('admins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister')),
            ],
            options={
                'db_table': 'AdminSelectedCategories',
            },
        ),
    ]
