# Generated by Django 3.2.9 on 2021-12-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0040_adminselectedcategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminselectedcategories',
            name='category_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
