# Generated by Django 3.2.9 on 2021-12-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0042_adminselectedcategories_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminselectedcategories',
            name='priority',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
