# Generated by Django 3.2.9 on 2021-12-10 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0044_alter_adminselectedcategories_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trending_category_name', models.CharField(max_length=200, unique=True)),
                ('trending_category_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('trending_category_image', models.FileField(blank=True, null=True, upload_to='CategoryImage')),
                ('trending_priority', models.CharField(blank=True, max_length=150, null=True)),
                ('admins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister')),
            ],
            options={
                'db_table': 'TrendingCategories',
            },
        ),
        migrations.CreateModel(
            name='TopTrendingCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, unique=True)),
                ('category_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('category_image', models.FileField(blank=True, null=True, upload_to='CategoryImage')),
                ('priority', models.CharField(blank=True, max_length=150, null=True)),
                ('admins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister')),
            ],
            options={
                'db_table': 'TopTrendingCategories',
            },
        ),
    ]
