# Generated by Django 3.2.9 on 2021-12-10 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0045_toptrendingcategories_trendingcategories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopTrendingCategories',
        ),
    ]
