# Generated by Django 3.2.9 on 2021-12-10 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0046_delete_toptrendingcategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingSubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trending_sub_category_name', models.CharField(max_length=200, unique=True)),
                ('trending_sub_category_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('trending_sub_category_image', models.FileField(blank=True, null=True, upload_to='CategoryImage')),
                ('trending_sub_priority', models.CharField(blank=True, max_length=150, null=True)),
                ('admins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister')),
            ],
            options={
                'db_table': 'TrendingSubCategories',
            },
        ),
        migrations.CreateModel(
            name='AdminSelectedSubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_name', models.CharField(max_length=200, unique=True)),
                ('sub_category_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('sub_category_image', models.FileField(blank=True, null=True, upload_to='CategoryImage')),
                ('sub_categories_priority', models.CharField(blank=True, max_length=150, null=True)),
                ('admins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister')),
            ],
            options={
                'db_table': 'AdminSelectedSubCategories',
            },
        ),
    ]
