# Generated by Django 3.2.3 on 2021-12-30 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0050_auto_20211230_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandcompanydetails',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='sellerordistributercommunicationdetails',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='basicsellerordistributerdetails',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.brandregistration'),
        ),
        migrations.AddField(
            model_name='brandcompanycommunicationdetails',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.brandregistration'),
        ),
        migrations.AddField(
            model_name='brandcompanydetails',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.brandregistration'),
        ),
        migrations.AddField(
            model_name='sellerordistributercommunicationdetails',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.brandregistration'),
        ),
    ]
