# Generated by Django 3.2.3 on 2021-12-30 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0051_auto_20211230_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandLegalDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_docs', models.FileField(upload_to='BrandFiles')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('admins', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.brandregistration')),
            ],
            options={
                'db_table': 'BrandLegalDocuments',
            },
        ),
    ]
