# Generated by Django 3.2 on 2021-08-03 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(max_length=100, unique=True)),
                ('plan_id', models.CharField(max_length=100, unique=True)),
                ('payment_id', models.CharField(max_length=100, unique=True)),
                ('period', models.CharField(max_length=100)),
                ('interval', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('entity', models.CharField(blank=True, max_length=100, null=True)),
                ('short_url', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'RazorpayModel',
            },
        ),
    ]
