# Generated by Django 3.2.3 on 2021-07-29 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(max_length=100, unique=True)),
                ('entity', models.CharField(blank=True, max_length=50, null=True)),
                ('period', models.CharField(max_length=100)),
                ('interval', models.CharField(max_length=100)),
                ('item', models.JSONField(blank=True, default=list, null=True)),
                ('item_id', models.CharField(max_length=100, unique=True)),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.BigIntegerField()),
                ('currency', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('item_created_at', models.IntegerField(blank=True, null=True)),
                ('item_updated_at', models.IntegerField(blank=True, null=True)),
                ('plan_created_at', models.IntegerField(blank=True, null=True)),
                ('notes', models.JSONField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('email_id', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PlanModel',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPlanModel',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('plan_id', models.CharField(db_index=True, max_length=100)),
                ('entity', models.CharField(blank=True, max_length=50, null=True)),
                ('period', models.CharField(max_length=100)),
                ('interval', models.CharField(max_length=100)),
                ('item', models.JSONField(blank=True, default=list, null=True)),
                ('item_id', models.CharField(db_index=True, max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.BigIntegerField()),
                ('currency', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('item_created_at', models.IntegerField(blank=True, null=True)),
                ('item_updated_at', models.IntegerField(blank=True, null=True)),
                ('plan_created_at', models.IntegerField(blank=True, null=True)),
                ('notes', models.JSONField(blank=True, null=True)),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('updated_on', models.DateTimeField(blank=True, editable=False)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('email_id', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical plan model',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
