# Generated by Django 3.2 on 2021-07-30 13:51

import SubscriptionApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubscriptionApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(max_length=100, unique=True)),
                ('payment_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(max_length=100, unique=True)),
                ('entity', models.CharField(blank=True, max_length=100, null=True)),
                ('plan_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('current_start', models.BigIntegerField(blank=True, null=True)),
                ('current_end', models.BigIntegerField(blank=True, null=True)),
                ('ended_at', models.BigIntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('notes', models.JSONField(blank=True, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('charge_at', models.BigIntegerField(blank=True, null=True)),
                ('start_at', models.BigIntegerField(blank=True, null=True)),
                ('end_at', models.BigIntegerField(blank=True, null=True)),
                ('auth_attempts', models.IntegerField(blank=True, null=True)),
                ('total_count', models.IntegerField()),
                ('paid_count', models.IntegerField(blank=True, null=True)),
                ('customer_notify', SubscriptionApp.models.CustomBooleanField(blank=True, default=1, null=True)),
                ('created_at', models.BigIntegerField(blank=True, null=True)),
                ('expire_by', models.BigIntegerField(blank=True, null=True)),
                ('short_url', models.CharField(blank=True, max_length=100, null=True)),
                ('has_scheduled_changes', models.BooleanField(blank=True, null=True)),
                ('change_scheduled_at', models.CharField(blank=True, default='now', max_length=100, null=True)),
                ('offer_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('remaining_count', models.IntegerField(blank=True, null=True)),
                ('notify_email', models.CharField(blank=True, max_length=100, null=True)),
                ('notify_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SubscriptionModel',
            },
        ),
    ]
