# Generated by Django 3.2 on 2021-08-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubscriptionApp', '0002_auto_20210805_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razorpaymodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
