# Generated by Django 3.1.5 on 2021-08-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubscriptionApp', '0003_alter_razorpaymodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razorpaymodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
