# Generated by Django 3.1.5 on 2021-07-14 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MastersApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdminApp', '0002_auto_20210714_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrytoservemaster',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hsnmaster',
            name='admins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister'),
        ),
        migrations.AddField(
            model_name='hsnmaster',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.createuser'),
        ),
        migrations.AddField(
            model_name='guaranteemaster',
            name='admins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister'),
        ),
        migrations.AddField(
            model_name='guaranteemaster',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.createuser'),
        ),
        migrations.AddField(
            model_name='frieghtchargesmaster',
            name='admins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister'),
        ),
        migrations.AddField(
            model_name='frieghtchargesmaster',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.createuser'),
        ),
        migrations.AddField(
            model_name='designationmaster',
            name='admins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister'),
        ),
        migrations.AddField(
            model_name='designationmaster',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.createuser'),
        ),
        migrations.AddField(
            model_name='departmentmaster',
            name='admins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister'),
        ),
        migrations.AddField(
            model_name='departmentmaster',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.createuser'),
        ),
        migrations.AddField(
            model_name='deliverymaster',
            name='admins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister'),
        ),
        migrations.AddField(
            model_name='deliverymaster',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.createuser'),
        ),
        migrations.AddField(
            model_name='currencymaster',
            name='admins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister'),
        ),
        migrations.AddField(
            model_name='currencymaster',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.createuser'),
        ),
        migrations.AddField(
            model_name='countrymaster',
            name='admins',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister'),
        ),
        migrations.AddField(
            model_name='countrymaster',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.createuser'),
        ),
        migrations.AddField(
            model_name='categorymaster',
            name='admins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister'),
        ),
        migrations.AddField(
            model_name='categorymaster',
            name='maincore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MastersApp.maincoremaster'),
        ),
        migrations.AddField(
            model_name='categorymaster',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.createuser'),
        ),
    ]
