# Generated by Django 3.2 on 2021-05-28 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminApp', '0002_initial'),
        ('MastersApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluommaster',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltaxmaster',
            name='admins',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AdminApp.adminregister'),
        ),
        migrations.AddField(
            model_name='historicaltaxmaster',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsupplycapabilitiesmaster',
            name='admins',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AdminApp.adminregister'),
        ),
        migrations.AddField(
            model_name='historicalsupplycapabilitiesmaster',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsubcategorymaster',
            name='admins',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AdminApp.adminregister'),
        ),
        migrations.AddField(
            model_name='historicalsubcategorymaster',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='MastersApp.categorymaster'),
        ),
        migrations.AddField(
            model_name='historicalsubcategorymaster',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsacmaster',
            name='admins',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AdminApp.adminregister'),
        ),
        migrations.AddField(
            model_name='historicalsacmaster',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpincodemaster',
            name='admins',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AdminApp.adminregister'),
        ),
        migrations.AddField(
            model_name='historicalpincodemaster',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpfchargesmaster',
            name='admins',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AdminApp.adminregister'),
        ),
        migrations.AddField(
            model_name='historicalpfchargesmaster',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalnatureofbusinessmaster',
            name='admins',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AdminApp.adminregister'),
        ),
        migrations.AddField(
            model_name='historicalnatureofbusinessmaster',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalindustrytoservemaster',
            name='admins',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AdminApp.adminregister'),
        ),
        migrations.AddField(
            model_name='historicalindustrytoservemaster',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalhsnmaster',
            name='admins',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AdminApp.adminregister'),
        ),
        migrations.AddField(
            model_name='historicalhsnmaster',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldesignationmaster',
            name='admins',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AdminApp.adminregister'),
        ),
        migrations.AddField(
            model_name='historicaldesignationmaster',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldepartmentmaster',
            name='admins',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AdminApp.adminregister'),
        ),
        migrations.AddField(
            model_name='historicaldepartmentmaster',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcurrencymaster',
            name='admins',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AdminApp.adminregister'),
        ),
        migrations.AddField(
            model_name='historicalcurrencymaster',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcategorymaster',
            name='admins',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AdminApp.adminregister'),
        ),
        migrations.AddField(
            model_name='historicalcategorymaster',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcategorymaster',
            name='maincore',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='MastersApp.maincoremaster'),
        ),
        migrations.AddField(
            model_name='designationmaster',
            name='admins',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister'),
        ),
        migrations.AddField(
            model_name='departmentmaster',
            name='admins',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister'),
        ),
        migrations.AddField(
            model_name='currencymaster',
            name='admins',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister'),
        ),
        migrations.AddField(
            model_name='categorymaster',
            name='admins',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister'),
        ),
        migrations.AddField(
            model_name='categorymaster',
            name='maincore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MastersApp.maincoremaster'),
        ),
    ]
