# Generated by Django 3.2 on 2021-08-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MastersApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrytoservemaster',
            name='industry_code',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='industrytoservemaster',
            name='industry_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='industrytoservemaster',
            name='status',
            field=models.CharField(default='Active', max_length=100),
        ),
    ]
