# Generated by Django 3.2 on 2021-06-21 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MastersApp', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpfchargesmaster',
            old_name='currency_code',
            new_name='pf_charge_code',
        ),
        migrations.RenameField(
            model_name='historicalpfchargesmaster',
            old_name='currency',
            new_name='pf_charge_description',
        ),
        migrations.RenameField(
            model_name='historicalpfchargesmaster',
            old_name='currency_id',
            new_name='pf_charge_id',
        ),
        migrations.RenameField(
            model_name='pfchargesmaster',
            old_name='currency_code',
            new_name='pf_charge_code',
        ),
        migrations.RenameField(
            model_name='pfchargesmaster',
            old_name='currency',
            new_name='pf_charge_description',
        ),
        migrations.RenameField(
            model_name='pfchargesmaster',
            old_name='currency_id',
            new_name='pf_charge_id',
        ),
        migrations.RemoveField(
            model_name='historicalpfchargesmaster',
            name='currency_name',
        ),
        migrations.RemoveField(
            model_name='pfchargesmaster',
            name='currency_name',
        ),
        migrations.CreateModel(
            name='WarrantyGuaranteeMaster',
            fields=[
                ('warranty_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('warranty_code', models.CharField(max_length=30, unique=True)),
                ('warranty_description', models.CharField(max_length=200, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Active', max_length=30)),
                ('admins', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.createuser')),
            ],
            options={
                'db_table': 'WarrantyGuaranteeMaster',
            },
        ),
        migrations.CreateModel(
            name='HistoricalWarrantyGuaranteeMaster',
            fields=[
                ('warranty_id', models.BigIntegerField(blank=True, db_index=True)),
                ('warranty_code', models.CharField(db_index=True, max_length=30)),
                ('warranty_description', models.CharField(db_index=True, max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('updated_on', models.DateTimeField(blank=True, editable=False)),
                ('status', models.CharField(default='Active', max_length=30)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('admins', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AdminApp.adminregister')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AdminApp.createuser')),
            ],
            options={
                'verbose_name': 'historical warranty guarantee master',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFrieghtChargesMaster',
            fields=[
                ('frieght_id', models.BigIntegerField(blank=True, db_index=True)),
                ('frieght_code', models.CharField(db_index=True, max_length=30)),
                ('frieght_description', models.CharField(db_index=True, max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('updated_on', models.DateTimeField(blank=True, editable=False)),
                ('status', models.CharField(default='Active', max_length=30)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('admins', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AdminApp.adminregister')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AdminApp.createuser')),
            ],
            options={
                'verbose_name': 'historical frieght charges master',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDeliveryMaster',
            fields=[
                ('delivery_id', models.BigIntegerField(blank=True, db_index=True)),
                ('delivery_code', models.CharField(db_index=True, max_length=30)),
                ('delivery_description', models.CharField(db_index=True, max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('updated_on', models.DateTimeField(blank=True, editable=False)),
                ('status', models.CharField(default='Active', max_length=30)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('admins', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AdminApp.adminregister')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AdminApp.createuser')),
            ],
            options={
                'verbose_name': 'historical delivery master',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FrieghtChargesMaster',
            fields=[
                ('frieght_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('frieght_code', models.CharField(max_length=30, unique=True)),
                ('frieght_description', models.CharField(max_length=200, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Active', max_length=30)),
                ('admins', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.createuser')),
            ],
            options={
                'db_table': 'FrieghtChargesMaster',
            },
        ),
        migrations.CreateModel(
            name='DeliveryMaster',
            fields=[
                ('delivery_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('delivery_code', models.CharField(max_length=30, unique=True)),
                ('delivery_description', models.CharField(max_length=200, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Active', max_length=30)),
                ('admins', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.createuser')),
            ],
            options={
                'db_table': 'DeliveryMaster',
            },
        ),
    ]
