# Generated by Django 3.2 on 2021-05-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MastersApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluommaster',
            name='uom_code',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='uommaster',
            name='uom_code',
            field=models.CharField(max_length=30),
        ),
    ]
