# Generated by Django 3.2 on 2021-06-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MastersApp', '0003_auto_20210621_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverymaster',
            name='delivery_code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='frieghtchargesmaster',
            name='frieght_code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldeliverymaster',
            name='delivery_code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfrieghtchargesmaster',
            name='frieght_code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpfchargesmaster',
            name='pf_charge_code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalwarrantyguaranteemaster',
            name='warranty_code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pfchargesmaster',
            name='pf_charge_code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='warrantyguaranteemaster',
            name='warranty_code',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
