# Generated by Django 3.2 on 2021-05-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MastersApp', '0003_auto_20210528_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhsnmaster',
            name='description_of_goods',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historicalhsnmaster',
            name='gst_rate_percentage',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalsacmaster',
            name='description_of_goods',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historicalsacmaster',
            name='gst_rate_percentage',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hsnmaster',
            name='description_of_goods',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hsnmaster',
            name='gst_rate_percentage',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sacmaster',
            name='description_of_goods',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sacmaster',
            name='gst_rate_percentage',
            field=models.CharField(max_length=200),
        ),
    ]
