# Generated by Django 3.2 on 2021-08-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MastersApp', '0003_auto_20210805_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='natureofbusinessmaster',
            name='nature_of_business_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='natureofbusinessmaster',
            name='status',
            field=models.CharField(default='Active', max_length=100),
        ),
    ]
