# Generated by Django 3.2 on 2021-08-09 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_alter_createuser_user_code'),
        ('MastersApp', '0004_auto_20210805_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionMaster',
            fields=[
                ('division_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('division_code', models.CharField(blank=True, max_length=40, null=True)),
                ('division_name', models.CharField(blank=True, max_length=100, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('admin_order', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(default='Active', max_length=30, null=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('admins', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.createuser')),
            ],
            options={
                'db_table': 'DivisionMaster',
            },
        ),
    ]
