# Generated by Django 3.2 on 2021-05-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MastersApp', '0004_auto_20210528_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltaxmaster',
            name='tax_percent',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltaxmaster',
            name='tax_slab_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='taxmaster',
            name='tax_percent',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='taxmaster',
            name='tax_slab_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
