# Generated by Django 3.2 on 2021-06-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MastersApp', '0005_corecategorymaster_historicalcorecategorymaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='corecategorymaster',
            name='core_category_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalcorecategorymaster',
            name='core_category_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
