# Generated by Django 3.2 on 2021-05-31 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MastersApp', '0005_auto_20210528_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencymaster',
            name='currency_name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcurrencymaster',
            name='currency_name',
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
