# Generated by Django 3.2 on 2021-08-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MastersApp', '0006_auto_20210817_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validitymaster',
            old_name='uupdated_by',
            new_name='updated_by',
        ),
        migrations.AlterField(
            model_name='deliverymaster',
            name='delivery_code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='deliverymaster',
            name='delivery_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='departmentmaster',
            name='department_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='designationmaster',
            name='designation_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='designationmaster',
            name='designation_short_text',
            field=models.CharField(blank=True, max_length=70, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='divisionmaster',
            name='division_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='frieghtchargesmaster',
            name='frieght_code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='frieghtchargesmaster',
            name='frieght_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='guaranteemaster',
            name='guarantee_code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='guaranteemaster',
            name='guarantee_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hsnmaster',
            name='description_of_goods',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hsnmaster',
            name='hsn_code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='inspectionmaster',
            name='inspection_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='itemgroupmaster',
            name='item_groups',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='liquidateddamagemaster',
            name='liquidated_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='natureofbusinessmaster',
            name='nature_of_business_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='paymentmaster',
            name='payment_terms',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='performanceguaranteesmaster',
            name='performance_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pfchargesmaster',
            name='pf_charge_code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='pfchargesmaster',
            name='pf_charge_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pricebasismaster',
            name='price_basis_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='rfqcategorymaster',
            name='rfq_category_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sacmaster',
            name='description_of_goods',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxesanddutiesmaster',
            name='tax_duties_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='taxmaster',
            name='tax_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='testandqapmaster',
            name='test_qap_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='transitinsurancemaster',
            name='transit_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='uommaster',
            name='uom_code',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='uommaster',
            name='uom_description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='uommaster',
            name='uom_short_text',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='validitymaster',
            name='validity_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='warrantymaster',
            name='warranty_code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='warrantymaster',
            name='warranty_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
