# Generated by Django 3.2 on 2021-06-23 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MastersApp', '0006_auto_20210623_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcorecategorymaster',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='historicalcorecategorymaster',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcorecategorymaster',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='CoreCategoryMaster',
        ),
        migrations.DeleteModel(
            name='HistoricalCoreCategoryMaster',
        ),
    ]
