# Generated by Django 3.2 on 2021-06-01 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdminApp', '0002_initial'),
        ('MastersApp', '0006_auto_20210531_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalindustrytoservemaster',
            name='created_by',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicalindustrytoservemaster',
            name='created_by_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalindustrytoservemaster',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalindustrytoservemaster',
            name='updated_by_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalnatureofbusinessmaster',
            name='nature_of_business_code',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='industrytoservemaster',
            name='created_by',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='industrytoservemaster',
            name='created_by_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industrytoservemaster',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='industrytoservemaster',
            name='updated_by_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='natureofbusinessmaster',
            name='nature_of_business_code',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='industrytoservemaster',
            name='admins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister'),
        ),
    ]
