# Generated by Django 3.2 on 2021-06-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MastersApp', '0007_auto_20210623_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluommaster',
            name='uom_code',
        ),
        migrations.RemoveField(
            model_name='uommaster',
            name='uom_code',
        ),
        migrations.AddField(
            model_name='historicaluommaster',
            name='uom_short_text',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uommaster',
            name='uom_short_text',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
