# Generated by Django 3.2 on 2021-08-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MastersApp', '0007_auto_20210817_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sacmaster',
            name='sac_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
