# Generated by Django 3.2 on 2021-06-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MastersApp', '0007_auto_20210601_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designationmaster',
            name='designation_level',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldesignationmaster',
            name='designation_level',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
