# Generated by Django 3.2 on 2021-06-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MastersApp', '0008_auto_20210624_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluommaster',
            name='uom_code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uommaster',
            name='uom_code',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
