# Generated by Django 3.2 on 2021-06-08 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_auto_20210607_1205'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MastersApp', '0008_auto_20210601_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalindustrytoservemaster',
            name='industry_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='industrytoservemaster',
            name='admins',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister'),
        ),
        migrations.AlterField(
            model_name='industrytoservemaster',
            name='industry_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='industrytoservemaster',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
