# Generated by Django 3.2 on 2021-08-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MastersApp', '0008_alter_sacmaster_sac_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfchargesmaster',
            name='pf_charge_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
