# Generated by Django 3.2 on 2021-08-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MastersApp', '0009_alter_pfchargesmaster_pf_charge_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfchargesmaster',
            name='pf_charge_description',
            field=models.CharField(max_length=200),
        ),
    ]
