# Generated by Django 3.2 on 2021-06-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MastersApp', '0010_countrymaster_historicalcountrymaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrymaster',
            name='country_flag',
            field=models.FileField(blank=True, null=True, upload_to='CountryFlags'),
        ),
        migrations.AddField(
            model_name='historicalcountrymaster',
            name='country_flag',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='countrymaster',
            name='country_name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='countrymaster',
            name='country_prefix',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcountrymaster',
            name='country_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcountrymaster',
            name='country_prefix',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
