# Generated by Django 3.2 on 2021-08-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MastersApp', '0011_auto_20210819_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guaranteemaster',
            name='guarantee_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='warrantymaster',
            name='warranty_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
