# Generated by Django 3.2 on 2021-06-26 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_initial'),
        ('MastersApp', '0011_auto_20210625_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrymaster',
            name='admins',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister'),
        ),
        migrations.AlterField(
            model_name='countrymaster',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.createuser'),
        ),
        migrations.AlterField(
            model_name='historicalsupplycapabilitiesmaster',
            name='supply_capability_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplycapabilitiesmaster',
            name='supply_capability_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
