# Generated by Django 3.2 on 2021-06-27 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdminApp', '0002_initial'),
        ('MastersApp', '0012_auto_20210626_1115'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalWarrantyGuaranteeMaster',
            new_name='HistoricalWarrantyMaster',
        ),
        migrations.RenameModel(
            old_name='WarrantyGuaranteeMaster',
            new_name='WarrantyMaster',
        ),
        migrations.AlterModelOptions(
            name='historicalwarrantymaster',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical warranty master'},
        ),
        migrations.AlterModelTable(
            name='warrantymaster',
            table='WarrantyMaster',
        ),
        migrations.CreateModel(
            name='HistoricalGuaranteeMaster',
            fields=[
                ('guarantee_id', models.BigIntegerField(blank=True, db_index=True)),
                ('guarantee_code', models.CharField(max_length=30, null=True)),
                ('guarantee_description', models.CharField(db_index=True, max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('updated_on', models.DateTimeField(blank=True, editable=False)),
                ('status', models.CharField(default='Active', max_length=30)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('admins', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AdminApp.adminregister')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AdminApp.createuser')),
            ],
            options={
                'verbose_name': 'historical guarantee master',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='GuaranteeMaster',
            fields=[
                ('guarantee_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('guarantee_code', models.CharField(max_length=30, null=True)),
                ('guarantee_description', models.CharField(max_length=200, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Active', max_length=30)),
                ('admins', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.createuser')),
            ],
            options={
                'db_table': 'GuaranteeMaster',
            },
        ),
    ]
