# Generated by Django 3.2 on 2021-08-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MastersApp', '0013_alter_deliverymaster_delivery_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentmaster',
            name='department_short_text',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
