# Generated by Django 3.2 on 2021-06-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MastersApp', '0013_auto_20210627_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymaster',
            name='category_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='historicalcategorymaster',
            name='category_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaincoremaster',
            name='maincore_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='historicalsubcategorymaster',
            name='sub_category_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='maincoremaster',
            name='maincore_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='subcategorymaster',
            name='sub_category_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
