# Generated by Django 3.2 on 2021-08-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MastersApp', '0014_alter_departmentmaster_department_short_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guaranteemaster',
            name='guarantee_description',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='warrantymaster',
            name='warranty_description',
            field=models.TextField(unique=True),
        ),
    ]
