# Generated by Django 3.2 on 2021-06-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MastersApp', '0014_auto_20210628_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymaster',
            name='status',
            field=models.CharField(default='Active', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalcategorymaster',
            name='status',
            field=models.CharField(default='Active', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaincoremaster',
            name='status',
            field=models.CharField(default='Active', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalsubcategorymaster',
            name='status',
            field=models.CharField(default='Active', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='maincoremaster',
            name='status',
            field=models.CharField(default='Active', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='subcategorymaster',
            name='status',
            field=models.CharField(default='Active', max_length=30, null=True),
        ),
    ]
