# Generated by Django 3.2 on 2021-06-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MastersApp', '0015_auto_20210628_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymaster',
            name='csv_category',
            field=models.FileField(blank=True, null=True, upload_to='MasterFile'),
        ),
        migrations.AddField(
            model_name='historicalcategorymaster',
            name='csv_category',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalindustrytoservemaster',
            name='csv_industry',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaincoremaster',
            name='csv_maincore',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalnatureofbusinessmaster',
            name='csv_nature',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalsubcategorymaster',
            name='csv_subcategory',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalsupplycapabilitiesmaster',
            name='csv_supply',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industrytoservemaster',
            name='csv_industry',
            field=models.FileField(blank=True, null=True, upload_to='MasterFile'),
        ),
        migrations.AddField(
            model_name='maincoremaster',
            name='csv_maincore',
            field=models.FileField(blank=True, null=True, upload_to='MasterFile'),
        ),
        migrations.AddField(
            model_name='natureofbusinessmaster',
            name='csv_nature',
            field=models.FileField(blank=True, null=True, upload_to='MasterFile'),
        ),
        migrations.AddField(
            model_name='subcategorymaster',
            name='csv_subcategory',
            field=models.FileField(blank=True, null=True, upload_to='MasterFile'),
        ),
        migrations.AddField(
            model_name='supplycapabilitiesmaster',
            name='csv_supply',
            field=models.FileField(blank=True, null=True, upload_to='MasterFile'),
        ),
    ]
