# Generated by Django 3.2 on 2021-08-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MastersApp', '0015_auto_20210819_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frieghtchargesmaster',
            name='frieght_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='frieghtchargesmaster',
            name='frieght_description',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
