# Generated by Django 3.2 on 2021-08-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MastersApp', '0016_auto_20210819_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverymaster',
            name='delivery_code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='deliverymaster',
            name='delivery_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='departmentmaster',
            name='department_short_text',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='divisionmaster',
            name='division_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='divisionmaster',
            name='division_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='frieghtchargesmaster',
            name='frieght_code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='frieghtchargesmaster',
            name='frieght_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='guaranteemaster',
            name='guarantee_code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='guaranteemaster',
            name='guarantee_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionmaster',
            name='inspection_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionmaster',
            name='inspection_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='itemgroupmaster',
            name='item_group_code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='liquidateddamagemaster',
            name='liquidated_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='liquidateddamagemaster',
            name='liquidated_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='natureofbusinessmaster',
            name='nature_of_business_code',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='natureofbusinessmaster',
            name='nature_of_business_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentmaster',
            name='payment_code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmaster',
            name='payment_terms',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='performanceguaranteesmaster',
            name='performance_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='performanceguaranteesmaster',
            name='performance_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pfchargesmaster',
            name='pf_charge_code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='pfchargesmaster',
            name='pf_charge_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pricebasismaster',
            name='price_basis_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='pricebasismaster',
            name='price_basis_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='rfqcategorymaster',
            name='rfq_category_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='rfqcategorymaster',
            name='rfq_category_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='supplycapabilitiesmaster',
            name='supply_capability_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='taxesanddutiesmaster',
            name='tax_duties_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='taxesanddutiesmaster',
            name='tax_duties_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='testandqapmaster',
            name='test_qap_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='testandqapmaster',
            name='test_qap_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='transitinsurancemaster',
            name='transit_code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transitinsurancemaster',
            name='transit_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='validitymaster',
            name='validity_code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='validitymaster',
            name='validity_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='warrantymaster',
            name='warranty_code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='warrantymaster',
            name='warranty_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
