# Generated by Django 3.2 on 2021-07-02 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MastersApp', '0016_auto_20210629_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGroupMaster',
            fields=[
                ('item_group_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_group_code', models.CharField(max_length=30, null=True)),
                ('item_groups', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='Active', max_length=30)),
                ('admins', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.createuser')),
            ],
            options={
                'db_table': 'ItemGroupMaster',
            },
        ),
        migrations.CreateModel(
            name='HistoricalItemGroupMaster',
            fields=[
                ('item_group_id', models.BigIntegerField(blank=True, db_index=True)),
                ('item_group_code', models.CharField(max_length=30, null=True)),
                ('item_groups', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('updated_on', models.DateTimeField(blank=True, editable=False)),
                ('created_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='Active', max_length=30)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('admins', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AdminApp.adminregister')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AdminApp.createuser')),
            ],
            options={
                'verbose_name': 'historical item group master',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
