# Generated by Django 3.1.5 on 2021-08-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MastersApp', '0017_auto_20210822_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantymaster',
            name='warranty_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
