# Generated by Django 3.2 on 2021-07-05 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0005_delete_imagemodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MastersApp', '0018_auto_20210703_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaltaxmaster',
            old_name='tax_group',
            new_name='tax_code',
        ),
        migrations.RenameField(
            model_name='taxmaster',
            old_name='tax_group',
            new_name='tax_code',
        ),
        migrations.AddField(
            model_name='currencymaster',
            name='currency_symbol',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='designationmaster',
            name='designation_short_text',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='historicalcurrencymaster',
            name='currency_symbol',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicaldesignationmaster',
            name='designation_short_text',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='historicaltaxmaster',
            name='CGST',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='historicaltaxmaster',
            name='IGST',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='historicaltaxmaster',
            name='SGST',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='taxmaster',
            name='CGST',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='taxmaster',
            name='IGST',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='taxmaster',
            name='SGST',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.CreateModel(
            name='ValidityMaster',
            fields=[
                ('validity_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('validity_code', models.CharField(max_length=30, null=True)),
                ('validity_name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='Active', max_length=30)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('admins', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.createuser')),
            ],
            options={
                'db_table': 'ValidityMaster',
            },
        ),
        migrations.CreateModel(
            name='TransitInsuranceMaster',
            fields=[
                ('transit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transit_code', models.CharField(max_length=30, null=True)),
                ('transit_name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='Active', max_length=30)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('admins', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.createuser')),
            ],
            options={
                'db_table': 'TransitInsuranceMaster',
            },
        ),
        migrations.CreateModel(
            name='PaymentMaster',
            fields=[
                ('payment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payment_code', models.CharField(max_length=30, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='Active', max_length=30)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('admins', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.createuser')),
            ],
            options={
                'db_table': 'PaymentMaster',
            },
        ),
        migrations.CreateModel(
            name='HistoricalValidityMaster',
            fields=[
                ('validity_id', models.BigIntegerField(blank=True, db_index=True)),
                ('validity_code', models.CharField(max_length=30, null=True)),
                ('validity_name', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('updated_on', models.DateTimeField(blank=True, editable=False)),
                ('created_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='Active', max_length=30)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('admins', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AdminApp.adminregister')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AdminApp.createuser')),
            ],
            options={
                'verbose_name': 'historical validity master',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTransitInsuranceMaster',
            fields=[
                ('transit_id', models.BigIntegerField(blank=True, db_index=True)),
                ('transit_code', models.CharField(max_length=30, null=True)),
                ('transit_name', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('updated_on', models.DateTimeField(blank=True, editable=False)),
                ('created_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='Active', max_length=30)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('admins', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AdminApp.adminregister')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AdminApp.createuser')),
            ],
            options={
                'verbose_name': 'historical transit insurance master',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPaymentMaster',
            fields=[
                ('payment_id', models.BigIntegerField(blank=True, db_index=True)),
                ('payment_code', models.CharField(max_length=30, null=True)),
                ('payment_terms', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('updated_on', models.DateTimeField(blank=True, editable=False)),
                ('created_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='Active', max_length=30)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('admins', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AdminApp.adminregister')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AdminApp.createuser')),
            ],
            options={
                'verbose_name': 'historical payment master',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
