# Generated by Django 3.1.5 on 2021-08-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MastersApp', '0018_auto_20210830_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guaranteemaster',
            name='guarantee_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
