# Generated by Django 3.2 on 2021-07-07 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MastersApp', '0019_auto_20210705_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubcategorymaster',
            name='maincore',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='MastersApp.maincoremaster'),
        ),
        migrations.AddField(
            model_name='subcategorymaster',
            name='maincore',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MastersApp.maincoremaster'),
            preserve_default=False,
        ),
    ]
