# Generated by Django 3.2 on 2021-07-10 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_imagemodel'),
        ('MastersApp', '0020_auto_20210707_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='RfqCategoryMaster',
            fields=[
                ('rfq_category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rfq_category_code', models.CharField(blank=True, max_length=40, null=True)),
                ('rfq_category_name', models.CharField(blank=True, max_length=100, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('admin_order', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(default='Active', max_length=30, null=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('admins', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.createuser')),
            ],
            options={
                'db_table': 'RfqCategoryMaster',
            },
        ),
    ]
