# Generated by Django 3.2.3 on 2021-11-15 05:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MastersApp', '0020_termmasterssettingsdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termmasterssettingsdescription',
            name='terms_description',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
