# Generated by Django 3.2 on 2021-07-12 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_imagemodel'),
        ('MastersApp', '0021_rfqcategorymaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAndQapMaster',
            fields=[
                ('test_qap_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('test_qap_code', models.CharField(blank=True, max_length=40, null=True)),
                ('test_qap_name', models.CharField(blank=True, max_length=100, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('admin_order', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(default='Active', max_length=30, null=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('admins', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.createuser')),
            ],
            options={
                'db_table': 'TestAndQapMaster',
            },
        ),
        migrations.CreateModel(
            name='TaxesAndDutiesMaster',
            fields=[
                ('tax_duties_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tax_duties_code', models.CharField(blank=True, max_length=40, null=True)),
                ('tax_duties_name', models.CharField(blank=True, max_length=100, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('admin_order', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(default='Active', max_length=30, null=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('admins', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.createuser')),
            ],
            options={
                'db_table': 'TaxesAndDutiesMaster',
            },
        ),
        migrations.CreateModel(
            name='PriceBasisMaster',
            fields=[
                ('price_basis_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price_basis_code', models.CharField(blank=True, max_length=40, null=True)),
                ('price_basis_name', models.CharField(blank=True, max_length=100, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('admin_order', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(default='Active', max_length=30, null=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('admins', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.createuser')),
            ],
            options={
                'db_table': 'PriceBasisMaster',
            },
        ),
        migrations.CreateModel(
            name='PerformanceGuaranteesMaster',
            fields=[
                ('performance_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('performance_code', models.CharField(blank=True, max_length=40, null=True)),
                ('performance_name', models.CharField(blank=True, max_length=100, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('admin_order', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(default='Active', max_length=30, null=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('admins', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.createuser')),
            ],
            options={
                'db_table': 'PerformanceGuaranteesMaster',
            },
        ),
        migrations.CreateModel(
            name='LiquidatedDamageMaster',
            fields=[
                ('liquidated_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('liquidated_code', models.CharField(blank=True, max_length=40, null=True)),
                ('liquidated_name', models.CharField(blank=True, max_length=100, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('admin_order', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(default='Active', max_length=30, null=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('admins', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.createuser')),
            ],
            options={
                'db_table': 'LiquidatedDamageMaster',
            },
        ),
        migrations.CreateModel(
            name='InspectionMaster',
            fields=[
                ('inspection_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('inspection_code', models.CharField(blank=True, max_length=40, null=True)),
                ('inspection_name', models.CharField(blank=True, max_length=100, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('admin_order', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(default='Active', max_length=30, null=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('admins', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.adminregister')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.createuser')),
            ],
            options={
                'db_table': 'InspectionMaster',
            },
        ),
    ]
