# Generated by Django 3.2.3 on 2021-11-15 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MastersApp', '0021_alter_termmasterssettingsdescription_terms_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TermMastersSettingsDescription',
        ),
    ]
