# Generated by Django 3.2.9 on 2022-01-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MastersApp', '0023_auto_20211122_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfchargesmaster',
            name='pf_charge_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
