# Generated by Django 3.2.9 on 2022-03-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MastersApp', '0024_alter_pfchargesmaster_pf_charge_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frieghtchargesmaster',
            name='frieght_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
