# Generated by Django 3.2 on 2021-06-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternalVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('internal_email', models.CharField(max_length=100)),
                ('internal_phone', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=500)),
                ('nature_of_business', models.CharField(max_length=100)),
                ('internal_status', models.CharField(default='Pending', max_length=30)),
                ('group', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'InternalVendor',
            },
        ),
    ]
