# Generated by Django 3.1.5 on 2021-07-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('nature_of_business', models.CharField(blank=True, max_length=500, null=True)),
                ('supply_capabilites', models.CharField(blank=True, max_length=500, null=True)),
                ('industry_to_serve', models.CharField(blank=True, max_length=500, null=True)),
                ('maincore', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=200, null=True)),
                ('send_status', models.CharField(default='Pending', max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField()),
            ],
            options={
                'db_table': 'BusinessRequest',
            },
        ),
        migrations.CreateModel(
            name='InternalBuyer',
            fields=[
                ('internal_buyer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_code', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('nature_of_business', models.CharField(blank=True, max_length=200, null=True)),
                ('email_id', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('maincore', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=200, null=True)),
                ('groups', models.CharField(blank=True, max_length=200, null=True)),
                ('registration_status', models.CharField(default='Not Registered', max_length=200)),
                ('approval_status', models.CharField(default='Pending', max_length=500)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField()),
            ],
            options={
                'db_table': 'InternalBuyer',
            },
        ),
        migrations.CreateModel(
            name='InternalVendor',
            fields=[
                ('internal_vendor_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_code', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=500)),
                ('city', models.CharField(blank=True, max_length=500, null=True)),
                ('state', models.CharField(blank=True, max_length=500, null=True)),
                ('nature_of_business', models.CharField(blank=True, max_length=500, null=True)),
                ('email_id', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=20)),
                ('maincore', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(blank=True, max_length=500, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=500, null=True)),
                ('groups', models.CharField(blank=True, max_length=500, null=True)),
                ('registration_status', models.CharField(default='Not Registered', max_length=500)),
                ('approval_status', models.CharField(default='Pending', max_length=500)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField()),
            ],
            options={
                'db_table': 'InternalVendor',
            },
        ),
        migrations.CreateModel(
            name='InviteVendor',
            fields=[
                ('invite_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email_id', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('registration_status', models.CharField(default='Not Registered', max_length=200)),
                ('approval_status', models.CharField(default='Pending', max_length=500)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('type_user', models.CharField(blank=True, max_length=80, null=True)),
                ('created_by', models.BigIntegerField()),
            ],
            options={
                'db_table': 'InviteVendor',
            },
        ),
    ]
