# Generated by Django 3.2 on 2021-07-07 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DashboardApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteVendor',
            fields=[
                ('invite_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email_id', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('registration_status', models.CharField(default='Not Registered', max_length=200)),
                ('approval_status', models.CharField(default='Pending', max_length=500)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField()),
                ('updated_by_invites', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'InviteVendor',
            },
        ),
        migrations.DeleteModel(
            name='InternalVendor',
        ),
    ]
