# Generated by Django 3.1.5 on 2021-07-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
