# Generated by Django 3.2 on 2021-07-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0003_auto_20210726_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
