# Generated by Django 3.2 on 2021-07-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0004_businessrequest_historicalbusinessrequest_historicalinternalbuyer_internalbuyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvitevendor',
            name='type_user',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='invitevendor',
            name='type_user',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
