# Generated by Django 3.2 on 2021-07-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0005_auto_20210711_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinternalvendor',
            name='category',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalinternalvendor',
            name='city',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalinternalvendor',
            name='company_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='historicalinternalvendor',
            name='email_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='historicalinternalvendor',
            name='groups',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalinternalvendor',
            name='maincore',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalinternalvendor',
            name='nature_of_business',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalinternalvendor',
            name='registration_status',
            field=models.CharField(default='Not Registered', max_length=500),
        ),
        migrations.AlterField(
            model_name='historicalinternalvendor',
            name='state',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalinternalvendor',
            name='sub_category',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='internalvendor',
            name='category',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='internalvendor',
            name='city',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='internalvendor',
            name='company_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='internalvendor',
            name='email_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='internalvendor',
            name='groups',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='internalvendor',
            name='maincore',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='internalvendor',
            name='nature_of_business',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='internalvendor',
            name='registration_status',
            field=models.CharField(default='Not Registered', max_length=500),
        ),
        migrations.AlterField(
            model_name='internalvendor',
            name='state',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='internalvendor',
            name='sub_category',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
