# Generated by Django 3.2.3 on 2021-07-12 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0006_auto_20210712_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinternalbuyer',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalinternalbuyer',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='historicalinternalvendor',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalinternalvendor',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='historicalinvitevendor',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalinvitevendor',
            name='updated_by_invites',
        ),
        migrations.DeleteModel(
            name='HistoricalBusinessRequest',
        ),
        migrations.DeleteModel(
            name='HistoricalInternalBuyer',
        ),
        migrations.DeleteModel(
            name='HistoricalInternalVendor',
        ),
        migrations.DeleteModel(
            name='HistoricalInviteVendor',
        ),
    ]
