# Generated by Django 3.2 on 2021-08-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0006_alter_businessrequest_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internalbuyer',
            old_name='category',
            new_name='industry_to_serve',
        ),
        migrations.RemoveField(
            model_name='internalbuyer',
            name='maincore',
        ),
        migrations.RemoveField(
            model_name='internalbuyer',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='businessrequest',
            name='email_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='businessrequest',
            name='gst_number',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='businessrequest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
