# Generated by Django 3.1.5 on 2021-08-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0007_auto_20210822_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
