# Generated by Django 3.1.5 on 2021-09-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0009_alter_businessrequest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
