# Generated by Django 3.2.9 on 2021-11-30 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0023_auto_20211103_1215'),
        ('DashboardApp', '0012_trailvendors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailvendors',
            name='company_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RegistrationApp.basiccompanydetails'),
        ),
        migrations.AlterField(
            model_name='trailvendors',
            name='created_by',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
