# Generated by Django 3.2.9 on 2021-12-15 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0023_auto_20211103_1215'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DashboardApp', '0013_auto_20211130_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_requirements', models.CharField(max_length=1000)),
                ('messages', models.TextField(blank=True, null=True)),
                ('quantity', models.CharField(max_length=50)),
                ('uom', models.CharField(max_length=100)),
                ('budget', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('company_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RegistrationApp.basiccompanydetails')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'QuoteModel',
            },
        ),
    ]
