# Generated by Django 3.2.9 on 2021-12-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0014_quotemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotemodel',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotemodel',
            name='users_city',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='quotemodel',
            name='users_company_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quotemodel',
            name='users_company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
