name: django-continuous-integration
on: [push]
jobs:
  simpleCheckout:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - name: Restart supervisor
        run: |
          cd /home/bvendorsinprod/actions-runner/_work/Bvsinprod 
          source myprojectenv/bin/activate
          cd Bvsinprod
          python manage.py collectstatic
          echo Vendorsin@2021@vsin | sudo -S systemctl restart gunicorn
          echo Vendorsin@2021@vsin | sudo -S systemctl restart nginx


     
