name: django-continuous-integration
on: [push]
jobs:
  simpleCheckout:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - name: Restart supervisor
        run: |
          echo Vendorsin@2021 | sudo -S systemctl restart gunicorn
          echo Vendorsin@2021 | sudo -S systemctl restart nginx
